CaravelGames/drod

DRODLib/Character.cpp
It's possible to set _MyScriptH to 4, and thus Generate Entity number four. But entity number four is the Nether. The Nether can only work in a handful of rooms, and never works if created via Generate Entity.
So if you try to generate the Nether, it should fail. This two line change makes this happen, by dropping out of Generate Entity if it attempts to create the Nether.
See: http://forum.caravelgames.com/viewtopic.php?TopicID=43247
=> Prevent Generate Entity from creating Nether

DROD/EditRoomWidget.cpp
People want bombs on open doors: http://forum.caravelgames.com/viewtopic.php?TopicID=44690
Since doors can be opened and closed, this PR also allows bombs to be place on closed doors. It's a lot more useful than putting them on solid walls.
=> Allow bombs to be placed on doors when editing

.gitignore, CompilingDrod_Win.md, DRODUtil/DRODUtil.cpp
- Rearrange gitignore folders into alphabetical order
- Add new folders to gitignore
- Add more clarity to troubleshooting issue for expat in build readme
- Fix compiler warning in DRODUtil regarding getch()
=> gitignore additions for VS2019 + compiler warning fix

CaravelNet/CaravelNet.2019.vcxproj, DRODLib/DRODLib.2019.vcxproj, DRODUtil/DRODUtil.2019.vcxproj
Note CaravelNet project was missing '..' include dir.
=> VS2019 project file include dir fixes.

DRODLib/CurrentGame.cpp, DRODLibTests/DRODLibTest.2019.vcxproj, DRODLibTests/src/tests/Monsters/Puff/PushFluffOntoTarstuffMother.cpp
Fix for: http://forum.caravelgames.com/viewtopic.php?TopicID=40928
The fix for unstable tarstuff not being removed after a puff was pushed onto mother-supported tarstuff was not applied to fluff. This meant bad tarstuff formations could be created.
Some tests have also been added to check situations where fluff and puffs are pushed onto tarstuff mothers.
=> Remove unstable tarstuff after pushing fluff onto tarstuff mother

drodrpg/DROD/EditRoomWidget.cpp
This removes a few restrictions on object placement, and adds a new restriction for stairs in the DROD RPG editor:
- Pits and Water can now be placed under tokens, to match tokens being able to be placed on these elements
- Bombs can now be placed on doors, and doors can be placed under bombs
- Stairs can no longer be placed under Level Entrances, to prevent malicious "Stair Loops"
=> DROD RPG: Update editor placement restrictions

DRODLib/DbRooms.cpp, DRODLib/TemporalClone.cpp, DRODLib/TemporalClone.h, DRODLibTests/src/tests/PlayerRoles/ConstructPlayerRole.cpp, DRODLibTests/src/tests/PlayerRoles/FegundoPlayerRole.cpp, DRODLibTests/src/tests/PlayerRoles/PuffPlayerRole.cpp
Fix for issues reported in http://forum.caravelgames.com/viewtopic.php?TopicID=42819
There is no test to see if Construct timeclones die on oremites. This is due to the test system failing in some unknown way to fully simulate DROD. The beheviour has been tested in game, and works there.
=> Temporal clone damage fix

DRODLib/CurrentGame.cpp, DRODLib/TileConstants.h, DRODLibTests/DRODLibTest.2013.vcxproj, DRODLibTests/src/tests/Player/Bugs/PushNPCOnBlockingTile.cpp
Pushing an NPC located on a generically impassable tile allowed the player to move onto the tile.
See: http://forum.caravelgames.com/viewtopic.php?TopicID=41547
=> Prevent Illegal NPC Pushing moves

DRODLib/DbRooms.cpp, DRODLibTests/DRODLibTest.2013.vcxproj, DRODLibTests/src/tests/TemporalToken/DoublePlacementPreventsRecording.cpp
This PR fixes the strange behavior described here: http://forum.caravelgames.com/viewtopic.php?TopicID=42966
Time Tokens will no longer activate if CSwordsman::wPlacingDoubleType isn't zero. This is probably preferable to the current behavior, which allows double placement to be repeated upon rewinding, and allows recording from arbitrary locations using clone potions.
=> Prevent Time Token activation on the same turn a player double is placed.

drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/Combat.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h
Based on this request, I suppose: http://forum.caravelgames.com/viewtopic.php?TopicID=41033
A little refactoring and a change so that adding Goblin Weakness or Wyrm Weakness to custom accessories works. This can be extended to support shields, but there's precedent for shields using behaviours in different ways, so I haven't added them for the moment.
=> DROD RPG: Make monster weakness behaviours function on accessories

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbPackedVars.h, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h, drodrpg/DRODLib/DbSavedGames.cpp, drodrpg/DRODLib/Monster.cpp, drodrpg/DRODLib/Monster.h
As per forum bug topic: http://forum.caravelgames.com/viewtopic.php?TopicID=43560
Also some related code hygiene:
LoadMonster now doesn't populate ExtraVars, as this isn't necessary.
Assert empty ExtraVars for non-character monsters on room import.
Refactor references to monster ExtraVars.
Refactor and remove SetExtraVarsFromMembers.
Rename SetMembersFromExtraVars -> SetMembers.
=> Fix ExtraVars overriding non-character monster stats in SetMonstersFromExploredRoomData().

DRODLib/CurrentGame.cpp, DRODLib/TemporalClone.cpp, DRODLib/TemporalClone.h
Fix for this report: http://forum.caravelgames.com/viewtopic.php?TopicID=44202
Temporal clones determine if their weapon should be active based on their identity. If this is set to a customer character, the identity will never be one that can weild a sword. This is inconsistent with the Swordsman, which uses "appearance" to determine if it can be armed. Appearance is based on the character type the custom character is based on.
By allowing temporal clones to have "appearance", this inconsistency can be fixed, allowing temporal clones of custom roles to use swords.
=> Retain sword state of custom player roles with temporal clones

DRODLib/DbRooms.cpp, DRODLibTests/src/tests/Scripting/Build/BuildingTarstuff.cpp
Fix for this report: http://forum.caravelgames.com/viewtopic.php?TopicID=44634
When tarstuff is constructed in a room by a Citizen, Engineer or script command, the game will later clean up any built tarstuff that's not stable. The function did not check if unstable tarstuff was no a mother, and would also remove that tarstuff.
A test has also been added for this situation.
=> Fix Tarstuff construction destroy mother-supported Tarstuff

drodrpg/DRODLib/DbSavedGames.cpp
In-room monster's (NPC's) ExtraVars does need to be loaded by saved game.
=> Revert bad change from monster stat fix.

.gitignore, drodrpg/DRODUtil/DRODUtil.cpp
More additions to gitignore when building the 2019 sln for RPG from a fairly new VS 2019 Community install.
Also fixes a minor compiler warning.
=> RPG gitignore additions

BackEndLib/BackEndLib.2019.vcxproj, CaravelNet/CaravelNet.2019.vcxproj, DROD/DROD.2019.vcxproj, DRODLib/DRODLib.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj, DRODUtil/DRODUtil.2019.vcxproj, FrontEndLib/FrontEndLib.2019.vcxproj, Master/Master.2019.sln, drodrpg/CaravelNet/CaravelNet.2019.vcxproj, drodrpg/DROD/Main.cpp, drodrpg/DROD/drod.2019.vcxproj, drodrpg/DRODLib/DRODLib.2019.vcxproj, drodrpg/DRODUtil/DRODUtil.2019.vcxproj, drodrpg/DRODUtil/GameScreenDummy.h, drodrpg/Master/Master.2019.sln
Add CaravelBuild build option.
Many other piecemeal project/build fixes (e.g., DRODUtil build fixes, Russian compile fix, add missing Steam include path, libs) and clean-up.
=> Correct DROD RPG DRODUtil project settings.

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h
See an example of this issue described here: http://forum.caravelgames.com/viewtopic.php?TopicID=41889
In addition to tokens not activating, I understand the issue could skip other events as well, such as queuing a question for processing or NPC scripts checking for an event occurring on room entrance.
=> Fix issues stemming from end-of-turn cue events and checks not being processed anytime the current room is initialized.

DROD/GameScreen.cpp
The original code would only set `stats` field of the temporary current game, which is immediattely overwrrited by the left-empty `statsAtRoomStart`. Happened in a call to `CCurrentGame::SetTurn(0)`, followed by `CCurrentGame::SetPlayerToRoomStart()` followed by `this->stats = this->statsAtRoomStart`.
The new solution will instead set `statsAtRoomStart` to the current game's `statsAtRoomStart` effectively exposing the variables in the previews.
=> Room preview from clicking on minimap now will have access to the current game's state variables (in a safe way).

BackEndLib/Wchar.cpp, BackEndLib/Wchar.h, DROD/CharacterOptionsWidget.cpp, DROD/CharacterOptionsWidget.h
I've tested that the changes to `_itoW` work correctly but please double check it. If you're worried about speed I'll gladly create another function that's safe.
[Relevant thread](http://forumskell.caravelgames.com/viewtopic.php?TopicID=44139).
=> Character processing seq buffer overflow

Texts/MIDs.h
It appears that during rebasing, some MID values got duplicated. I've removed the extras, allowing the TSS 5.2 branch to build again.
=> Remove duplicated MID values

DROD/TileImageCalcs.cpp, DROD/TileImageCalcs.h
This PR fixes http://forum.caravelgames.com/viewtopic.php?TopicID=39612.
As Halph and Young Halph share graphics they were both marked as having wading graphics. However, Young Halph cannot wade, but wading graphics were still being drawn when Young Halph is killed by being pushed into shallow water.
=> fix: don't draw wading tiles for Young Halph

DRODLib/Mimic.cpp
Fix for a build problem. This also occurs in the 5.2 branch, so an additional merge will be required
=> Fix missing () on function call in Mimic.cpp

DROD/RoomWidget.cpp
That is, the player's light should not be getting refreshed while a double is being placed.
=> Fix player light rendering glitches when placing a double in a dark room.

DROD/Chat.h, FrontEndLib/ListBoxWidget.h, FrontEndLib/SubtitleEffect.h, drodrpg/DROD/Chat.h
The way the default black color was set in some instances caused issues on OS X, where the color would not always be set correctly, resulting in text not being visible in list boxes. I've changed the constructors using this logic to fix the issue.
=> fix: set default black color in different manner to ensure it is always set correctly

DROD/DrodScreen.cpp, DROD/GameScreen.cpp
Turns out the methods that add stun effects didn't actually check if the monster at that location is stunned, it just checks if it's alive. If a character is pushed to a square and then immediately killed, `pMonster` is actually the killing monster and a stun effect should not be drawn. The explicit `isStunned` check remedies this.
=> fix: check if monster in square where stun effect is being applied is actually stunned

DROD/CharacterDialogWidget.cpp, DROD/CreditsScreen.cpp, DROD/FaceWidget.cpp, DROD/FaceWidget.h, DROD/GameScreen.cpp, DROD/GameScreen.h, DRODLib/CharacterCommand.cpp, DRODLib/CharacterCommand.h
Why: I was chasing a bug, where the game would not switch back from custom image avatar to a built-in avatar if you changed player roles. Then when I fixed it something else broke. And then I fix what broke and yet another thing broke. Then I realized the way FaceWidget is written and used is flawed in two ways.
Flaw 1 - trying to fit as much state in as few variables. There was the whole thing with locking moods which was made to not have to have separate set of variables for speakers, which was the main source of issues.
Flaw 2 - a lot of logic that belonged in `FaceWidget` was spread around `GameScreen` , specifically figuring out how to manipulate the moods and the locks.
Analysis - when you think about it, there are essentially three differnt things displayed in the widget. Player's …
=> A big rewrite of FaceWidget.

BackEndLib/BackEndLib.2019.vcxproj, CaravelNet/CaravelNet.2019.vcxproj, DROD/DROD.2019.vcxproj, DROD/ImageOverlayEffect.cpp, DRODLib/DRODLib.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj, DRODUtil/DRODUtil.2019.vcxproj, FrontEndLib/EventHandlerWidget.cpp, FrontEndLib/FrontEndLib.2019.vcxproj, FrontEndLib/Screen.cpp, FrontEndLib/Screen.h
Added static fields to `CScreen`. One of them is used to replace calls to SDL_Ticks() to ensure effects play synchronized, rather than desyncing in edge cases when ticks crosses a threshold to the next millisecond. Added two more variables which I will be using in future code
Also enabled multiprocessor compilation and incremental linking because they speed things up a lot.
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44754)
=> Synchronized Image Overlay effects + multiprocessor compilation

DRODLib/Character.cpp, DRODLib/CurrentGame.cpp, DRODLib/DbRooms.cpp, DRODLib/DbRooms.h, DRODLib/Monster.cpp, DRODLib/Monster.h
Made CRoom::DeadMonsters list be cleared every turn of monsters that are not needed anymore
And dead/ended invisible scripts are also removed from the room.
Previously DeadMonsters was only cleared once upon room object destruction. This caused issues with rooms that do some really heavy scripting and create a lot of temporary characters. Now dead monsters are deleted every turn, except the ones which must persist for longer because they might be processed by frontend for longer. Notably it seems the only case is Speech.
I've carefully inspected every usage of CueEvents private data and failed to find any other situation where a monster attached to an event is stored for future use except speech. Right now the characters used in speech are not 'released' until the room is deleted which …
=> Memory usage optimizations

drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/EntranceSelectDialogWidget.cpp, drodrpg/DROD/EntranceSelectDialogWidget.h
When F4 is pressed during playtesting, a list of all game variables is displayed with their values. From this list, the values can be edited.
This PR extends the list to include hold variables, allowed them to be viewed and editing, both with integer and string values. Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=41659
=> RPG: Allow editing of hold variables in Global Variable Editor

DROD/EditSelectScreen.cpp, FrontEndLib/FocusWidget.cpp, FrontEndLib/Widget.cpp, FrontEndLib/Widget.h
- It is no longer possible to change map's display type for a hold you don't own
- It is no longer possible to change map image for a hold you don't own
- When in EditSelectScreen you change from a hold that has world map to one that is not editable, map buttons become disabled now
- It's no longer possible to change 'Show Exit level' for a hold you don't own
- UI elements in EditSelectScreen will no longer be redrawn on top of different elements when changing tabs and focus is on the element outside the tabbed interface
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=42247)
=> Editor ui issues

DROD/CharacterDialogWidget.cpp
While you can technically use `If` commands on `Move` and `Move To`, the functionallity that occurs is a side-effect of how movement commands work. Marking these commands with `?` in the script editor warns of this.
See thread: http://forum.caravelgames.com/viewtopic.php?TopicID=38550
=> Mark movement commands as questionable ifs

DRODLib/BuildUtil.cpp, DRODLib/Citizen.cpp, DRODLib/Station.cpp, DRODLib/Station.h, DRODLibTests/DRODLibTest.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj.filters, DRODLibTests/src/RoomBuilder.cpp, DRODLibTests/src/RoomBuilder.h, DRODLibTests/src/tests/Scripting/Build/BuildingRelayStations.cpp
When Relay Stations are built, they are not added to `CDBRoom::stations`. This means they are never used by citizens. By adding them when construction occurs, they now work.
Additionally, this PR implements a request to make Relay Stations constructed by Citizens inherit the constructing citizen's group.
Bug thread: http://forum.caravelgames.com/viewtopic.php?TopicID=44680
Feature thread: http://forum.caravelgames.com/viewtopic.php?TopicID=44681
=> Make constructed Relay Stations functional and match Citizen group

DRODLib/BuildUtil.cpp, DRODLib/BuildUtil.h
⚠ Review this after #220 is merged, since this branch depends on changes from that PR.
[Relevant thread 1](http://forum.caravelgames.com/viewtopic.php?TopicID=41060)
[Relevant thread 2](http://forum.caravelgames.com/viewtopic.php?TopicID=34576)
=> Bridge build fixes

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterDialogWidget.h
In mainline DROD, some script commands are drawn with different colours to improve readability. Since the support for this comes from `FrontEndLib`, I've setup DROD RPG to do it is as well. I've setup the three `Each <event>` commands to have the same colour as `Go To`, but that can be changed if we want.
I've also set it so that the Command List, Item List and Visual Effects list widgets are sorted alphabetically, and enabled hotkey selection for them. This is because I keep trying to use hotkey selection in the DROD RPG editor and it doesn't work, which is annoying.
=> RPG: Script command colouring and addition hotkeyable lists

drodrpg/DROD/EditRoomScreen.cpp
Muti-use plates are fully implemented in DROD RPG, as far as I can tell. So the only thing that needs to be done is to make them selectable in the editor by re-enabling object rotation for pressure plates, and setting it up so that one-use plates can't be selected.
=> Allow multi-use plates to be selected in DROD RPG editor

DROD/ClockWidget.cpp, DRODLib/DbXML.cpp, DRODLib/DbXML.h, FrontEndLib/SubtitleEffect.cpp
[Relevant issue](https://forum.caravelgames.com/viewtopic.php?TopicID=38449)
This PR addresses OOM errors when attempting to export and import very large .player files (and possibly also .hold files, etc).
Here's what's in this change, which I welcome your feedback on if you have thoughts/opinions:
* Up till now, when exporting, all the data being compiled into the file is first concatenated into a text string in RAM, which is then zlib-compressed into another buffer in RAM, and then CStretchyBuffer-encoded, then written to a file on disk.  Large player profiles (or maybe holds) can run out of memory (in the 32-bit address space in our Windows build) during export.
* To mitigate this, I've changed the export process to use gzip verbs (instead of zlib format), which allow writing of …
=> Reduce memory footprint on export and import to avoid OOM issues.

DRODLib/DbRooms.cpp
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44790)
=> Dagger will no longer prevent tar babies from growing

DROD/DrodScreen.h, DROD/GameScreen.cpp, DROD/GameScreen.h, DROD/RoomWidget.cpp, FrontEndLib/DialogWidget.cpp, FrontEndLib/DialogWidget.h, FrontEndLib/EventHandlerWidget.cpp, FrontEndLib/EventHandlerWidget.h
- Undoing while a infinitely looping overlay is playing every turn won't duplicate the effect for one turn
-  Effects now pause correctly when speech log is opened and resume when it's closed. Everything also works correctly with losing and regaining focus.
- Chat history dialog will also pause effects and audio now"
-  Finally, dialogs will delegate handling windows focus back to their parent (who should either be a screen or another dialog, which in turn will delegate it all the way back to a screen). This allows having special handling for focus, eg. repausing sound if dialog is open
----
Marked as draft since it depends on changes from #228 and #245.
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44825)
=> Image overlay bugs

FrontEndLib/BumpObstacleEffect.cpp
- It will no longer populate the draw surface on update, which caused it to pull incorrect surface. This caused a bug when bumping a killing monster - the bump would just draw whiteish square.
- It will now regenerate on every draw to remove weird visual artifacts
- Bumping again Row 0 / Col 0 would produce no effect, this is also fixed
[Relevant thread 1](http://forum.caravelgames.com/viewtopic.php?TopicID=44833)
[Relevant thread 2](http://forum.caravelgames.com/viewtopic.php?TopicID=40737)
[Relevant thread 3](http://forum.caravelgames.com/viewtopic.php?TopicID=41029)
=> Bump effect fixes.

DROD/AumtlichGazeEffect.cpp, DROD/GameScreen.cpp, DROD/GameScreen.h, DROD/RoomWidget.cpp
Aumtlich beams now render during double placement + further cleanup in rendering logic
Previously placing doubles would have a lot of duplicate logic to, I
presume, improve rendering speed by caching almost the whole screen.
This had a couple of problems:
1. A lot of duplicate logic made it very difficult to understand what is
happening where.
2. It was easy to forget to keep both up to date.
As such I refactored it so that it uses common rendering path
----
Depends on PR #246, posting as draft.
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=33595)
=> Aumtlich beams double placement

BackEndLib/Files.cpp, BackEndLib/Files.h, DROD/Main.cpp, drodrpg/DROD/Main.cpp
To address Metakit filepath issue not working for Windows Steam users w/ non-ascii chars in their username.
=> Windows: Command line option to change default player data dir location.

DROD/GameScreen.cpp, DROD/ImageOverlayEffect.cpp, DROD/RoomWidget.cpp, DROD/RoomWidget.h, FrontEndLib/EffectList.cpp, FrontEndLib/EffectList.h
Reworked death animation to no longer cache most of the room in a surface and doing shenanigans with effects and other things which caused a lot of issues with image overlays on lower levels, some effects not playing etc. This also makes the death animations much smoother.
[Relevant thred](http://forum.caravelgames.com/viewtopic.php?TopicID=44801)
----
Essentially that will mean death animation will be slightly more CPU intensive, but it will be smoother and all effects will play and there will be no issues with lower-layer image overlays suddenly appearing on top of other things.
=> Death revamp

BackEndLib/Files.cpp, BackEndLib/Files.h, DRODLib/Guard.cpp, DRODLib/Monster.cpp, DRODLibTests/src/CTestDb.cpp, DRODLibTests/src/Runner.cpp, DRODLibTests/src/tests/Monsters/ArmedMonsters/RearmedGuards.cpp
- Guards with daggers can now dagger step vulnerable characters regardless of their appearance
- Also tests were broken by the Ascii -> Utf8 change so I fixed them 
- Fixed the assertion that kept failing during test teardown since forever
- Also tests are now  guaranteed to run with their own dats
=> Guards with daggers

DROD/EditRoomScreen.cpp, DROD/RoomScreen.cpp
LastNotice is used by the HoldSelectScreen to determine if there have been any hold update notices received since the last refresh.  As such, only HoldSelectScreen should update this value.
=> Fixed the LastNotice flag being updated when it shouldn't

DROD/EditRoomWidget.cpp, DROD/RoomWidget.cpp, DROD/RoomWidget.h, DROD/SteamEffect.cpp, DROD/StrikeOrbEffect.cpp, DROD/StrikeOrbEffect.h, DROD/TemporalMoveEffect.cpp, DROD/VarMonitorEffect.cpp, FrontEndLib/DialogWidget.cpp, FrontEndLib/DialogWidget.h, FrontEndLib/Widget.h
- O-layer effects dirty room at the end of room drawing to avoid artifacts being left
- Temporal projection preview no longer assertion beeps
- Steam Effect now draws again
- Var Monitor no longer redraws every turn when no changes to variables
were detected
- Strike orb effect will no longer leave artifacts when triggered by
one-use plate or cracked orb
- Dialogs which attach to RoomWidget (Current Game Info) will no longer
assert beep when getting/losing focus
- In the editor characters' swords will not flicker or disapper when
sub menus are opened
- Removed dead code `CRoomWidget::PutTLayerEffectsOnMLayer()`
----
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44919)
=> Fixes to effect and rendering:

DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/DbRooms.cpp, DRODLibTests/src/Runner.h
This compacts the checks for character behaviors into a single function. Places that used to check `behaviorFlags` now use the `HasBehavior()` function. This should makes things a little more readable, and means if things outside of the character class need to check for behaviors, they can.
There's also a bit of tidying up, including plugging `CanPressPressurePlates()` into a place it should be used.
=> Refactor logic for checking behaviors

FrontEndLib/BitmapManager.cpp, FrontEndLib/BitmapManager.h, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DRODLib/DRODLib.2019.vcxproj.filters, drodrpg/DRODLib/DbRooms.cpp
[Relevant topic](https://forum.caravelgames.com/viewtopic.php?TopicID=44947)
Multiple changes here.  Check out the commit diffs individually for the recommended way to follow the changes.
If this looks good to you, I'll migrate these fixes to 5.1.1.
=> RPG: Fix regression in smooth lighting animation on moving pit platforms.  Other lighting fixes and improvements.

BackEndLib/Wchar.h, DROD/GameScreen.cpp, FrontEndLib/BitmapManager.h, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h
[Relevant topic](https://forum.caravelgames.com/viewtopic.php?TopicID=44953)
There were multiple issues with the clipping and lighting logic at the room boundary.  These changes are much easier to see with the larger tiles of RPG.
Once reviewed and approved, I can migrate these changes to 5.x.
=> RPG: Correct errors in clipping logic and light application for sprites moving across room boundary.

DROD/HoldSelectScreen.cpp, DROD/RoomScreen.cpp, DROD/RoomScreen.h, DRODLib/NetInterface.h
This makes the buttons on the notices popup do something:
- The delete button removes the selected notice from the list
- The watch button will do different things depending on the type of notice:
-- Hold release/update - take user to hold select screen with the new/updated hold selected
-- URL - open a browser with the selected URL.  Currently there are no notices that use this, but now we can add them!
-- There is a third type defined in DROD that we also haven't used, one that specifies a room.  The main idea was to have a "your #1 score was beaten" notice, and the button would take you to that room if installed & available.  
Relevant thread: https://forum.caravelgames.com/viewtopic.php?TopicID=39139
=> Added some functionality to the buttons on the notices popup

drodrpg/DROD/KeypressDialogWidget.cpp, drodrpg/DROD/KeypressDialogWidget.h
#327 removed `KeypressDialogWIdget` from frontendlib and moved it to each game's respective DROD project, but I forgot to add the relevant files for RPG.
=> Added files that I forgot to commit while doing keymap revampin DROD

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterDialogWidget.h, drodrpg/DRODLib/CharacterCommand.cpp, drodrpg/DRODLib/CharacterCommand.h
1. I refactored `CCharacterDialogWidget::SetActionWidgetStates()` in the DROD RPG code to match the mainline version. Now you can see what widgets a group has at a glance, and added new widgets more easily.
2. While it's possible to use Smart Labels in the `Each <Event>` script commands, doing so is likely to lead to unclear execution based on the implementation details of the smart labels. This isn't very user friendly, so when any of the `Each <Event>` commands are selected, the smart labels are removed from the list.
=> Refactor RPG character dialog and prevent use of Smart Labels in Each Event commands

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h
Also:
* Script command phantom data fix
* Tool tip display fix
=> RPG: Fix regression in temporary room display where player interacts with room (e.g., collecting an item).

DROD/RoomWidget.cpp, DRODLib/Halph.h
Halph's pathing is weird and confusing to many players. So there is a desire to visualize it. Using [code provided by bbb](http://forum.caravelgames.com/viewtopic.php?TopicID=44932&page=0#437954), this visualisation can now occur.
=> Allow players to view the path of Halphs

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CurrentGame.cpp
Testing for DROD RPG 1.3 has found an issue with pressure plates and characters with changed movement types: http://forum.caravelgames.com/viewtopic.php?TopicID=29976&page=0#438113. Additionally, character movement type is not serialized, but now needs to be.
Currently, when a monster is created or a room is loaded, pressure plate state is set before character scripts are run. This needs to be slightly delayed, so that characters with changed movement types correctly interact with plates on turn zero.
=> RPG: Fix issues with changed monster movement types

drodrpg/DRODLib/Character.cpp
Due to changes related to setting character movement, wall and water dwelling characters can no longer move over regular floors, which is wrong. This PR fixes this.
=> RPG: Fix regression in CCharacter::IsTileObstacle()

drodrpg/DROD/RoomWidget.cpp
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45005
The case where a character had an identity less than `CHARACTER_FIRST` was missed, meaning regular monster characters did not return the correct name.
=> RPG: Characters as monsters don't have a name

FrontEndLib/ListBoxWidget.cpp
Fixes the issues described in #378. An additional line is needed so that the change to the item order is also applied to the filter items which are shown to the user.
=> Fix drag and drop functionallity in script editor

DROD/RoomWidget.cpp, DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, DRODLib/Halph.h, DRODLib/Monster.h
Stalwart, Soldier and Citizen pathfinding is weird and confusing to many players. So there is a desire to visualize it. It would also be nice if clicking on horns showed where the spawn will occur.
Monster path visuals extend the implementation of #359, allowing paths to be viewed for Stalwarts, Soldiers, Citizens and Engineers.
=> Additional object selection highlighting

DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, DRODLib/PlayerStats.cpp, DRODLib/PlayerStats.h, DRODLib/TileConstants.h, DRODLibTests/DRODLibTest.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj.filters, DRODLibTests/src/tests/Scripting/PrimitiveFunctions.cpp, Data/Help/1/refindex.html, Data/Help/1/script.html
It's #354, but for mainline DROD. Adds functions that be used when setting variables. I consider the functions to exist in three categories.
For the manipulation of numbers or calculation of values.
`_abs(x)` - Returns the absolute value of x
`min(x,y)` and `max(x,y)` - Returns the lesser and greater value, respectively.
`_dist0(x1,y1,x2,y2)` - Distance between two points using L-infinity metric
`_dist1(x1,y1,x2,y2)` - Distance between two points using L1 metric
`_dist2(x1,y1,x2,y2)` - Distance between two points using L2 metric
Number crunching, in specific DROD contexts
`_ox(o)` and `_oy(o)` - Returns x and y components of the given orientation. Invalid orientations return themselves
`_orient(x,y)` - Returns the orientation based on the given x and y component
`_facing(dx,dy)` - Returns …
=> Add script expression parsing support for primitive functions with parameter lists

DROD/CharacterDialogWidget.cpp, DROD/CharacterDialogWidget.h, DROD/DROD.2019.vcxproj, DROD/DROD.2019.vcxproj.filters, FrontEndLib/ListBoxWidget.cpp, FrontEndLib/ListBoxWidget.h, drod/CommandListBoxWidget.cpp, drod/CommandListBoxWidget.h
This depends on changes from #353.
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=39965&page=0#437953)
=> Command list improvs

DROD/CharacterDialogWidget.cpp, DROD/CharacterDialogWidget.h
#357 adds a number of visual improvements to script editing. However, it was overlooked that `CCharacterDialogWidget` actually has _two_ lists of commands - one for the character's script, and one for editing default scripts. The changes for #357 only apply to the main editor's listbox, meaning that it will be incorrectly referenced while editing default scripts. This crashes DROD due to out-of-bounds errors if the default script being edited is longer than the character script.
I've gone through and fixed that, and also updated the default script editor's list to be a `CCommandListBoxWidget`
=> Fix improved script editor to work with default script editing

drodrpg/DRODLib/DbRooms.cpp
Preview bomb explosion calls CDbRoom::ConvertUnstableTar(). This function needs an active game to work, so a crash happens. Confusingly, it only crashs in the alpha. Anyhow, I updated the function to match the mainline version for getting player co-ordinates to avoid a crash.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45237
=> RPG: Fix crash when clicking bomb in editor

DROD/FaceWidget.cpp, Data/Help/1/character.html
A small change to face drawing code to support moods for custom portraits. The face's mood value is used to offset the source rectangle (provided the image is wide enough), allowing a custom portrait to provide graphics for moods other than normal.  In additional to speaking moods, it also means that a custom dying mood can be provided for custom player roles.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=41611
=> Support moods for custom portraits

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CreditsScreen.cpp, drodrpg/DROD/FaceWidget.cpp, drodrpg/DROD/FaceWidget.h, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/GameScreen.h, drodrpg/DROD/RoomWidget.cpp, drodrpg/Data/Help/1/customchar.html
Updates the face management code in DROD RPG to the newer DROD 5.0 face management. This makes faces better, I assume.
Also includes the small change to face drawing code to support moods for custom portraits. The face's mood value is used to offset the source rectangle (provided the image is wide enough), allowing a custom portrait to provide graphics for moods other than normal.
=> RPG: Support moods for custom portraits

DRODLib/Monster.cpp
#329 includes a fix to `CMonster::ConfirmPath()` to prevent assertion beeps when the monster is on the path. It does so by skipping the check for the tile containing the monster, preventing the path from being regenerated in this case. A comment claims this is to prevent demo breakage. The given fix is wrong for two reasons:
1. Prior to this change, a monster on it's own path would cause the path to regenerate. If any of the monsters that use `ConfirmPath()` call `DoesSquareContainObstacle()` on their own tile, it will return true, as the tile contains a monster, which is an obstacle. This then invalidates the path. Therefore, not invaliding the path changes the current behavior, and could cause demo breaks.
2. Allowing a monster's path to contain the tile it is on means that the monster …
=> Fix CMonster::ConfirmPath() for when monster is on its own path

DRODLib/CurrentGame.cpp
In a few cases, Halph and Slayers can entry a on from a room edge tile in a weird way:
1. When entering at a corner, they are treated as moving diagonally by arrows, but not by orthosquares. This has been corrected so that a corner entry is blocked by an orthosquare. If the orthosquare is later removed, they will then be able to enter.
2. They can enter the room on an active fire trap, which is instantly lethal and inconsistent with how both elements avoid active traps. This has been corrected so that active traps block them from entering the room.
3. They can enter the room on a puff. This leads to two monsters sharing a tile, which is not good. This has been corrected so that puffs also block them from entering the room.
Related thread with discussion: …
=> Add additional restrictions to Halph/Slayer room entry

DROD/CharacterDialogWidget.cpp, DROD/DrodScreen.cpp, DROD/ImageOverlayEffect.cpp, DROD/ImageOverlayEffect.h, DROD/RoomEffectList.cpp, DROD/RoomEffectList.h, DROD/RoomWidget.cpp, DROD/RoomWidget.h, DRODLib/CharacterCommand.cpp, DRODLib/CharacterCommand.h, DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, Data/Help/1/script.html
Implements most of the Image Overlay commands requested in #71:
`AddX` and `AddY` move the the image by the given amount in the given axis.
`DisplayRectModify` allows the source region of the image to be altered
`Group` and `CancelGroup` allows images to be assigned to a group that can be cleared at a later point.
=> Additional Image Overlay commands

DRODLib/GameConstants.cpp
This fixes a typo in the key to command mapping that means the command to switch the active player instead restarts the room.
=> Fix clone switch command assignment

DRODLib/Character.cpp
Fix for minor problem in #387, where the first command in a default script will be skipped due to the command index incrementing after the script is replaced with the default script. Automatic increment is supressed for the command. If the replacement fails, the index is manually incremental to prevent the script runner getting stuck.
=> Don't increment command index after default script replacement

drodrpg/DRODLib/CurrentGame.cpp
Attempting to show a hold or level's statistics in the editor using F3 or F4 causes DROD to crash. This occurs in `CCurrentGame::GetGlobalStatModifier()`, as it attempts to acquire the room modifier for the HP stat. This fails, as there is no active room.
Adding a check that `pRoom` is not null before calling `CDbRoom::GetStatModifierFromCharacters()` prevents this crash from occuring.
Reporting thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45323
=> RPG: Fix crash when showing level or hold stats in editor

drodrpg/DROD/RestoreScreen.cpp
The sort list widget was five units too small, causing an assert to fire whenever it was created or interacted with. Making it a smidge bigger fixes this.
Reporting thread: http://forum.caravelgames.com/viewtopic.php?TopicID=44992
=> RPG: Fix assert on Restore screen

drodrpg/DRODLib/Monster.cpp
The changes in #373 to support NPC egg spawning include a change to egg spawning code to handle monsters without an orientation. This had the side effect of causing roach eggs to spawn fully grown, as they don't have an orientation, but their orientation value is used to decide how the egg is drawn. To fix this, eggs are exempt from the orientation fixing, which they do not require.
Reporting post: http://forum.caravelgames.com/viewtopic.php?TopicID=44943&page=0#441141
=> RPG: Fix orientation of spawned eggs

DRODLib/Citizen.cpp, DRODLib/Halph.cpp, DRODLib/Slayer.cpp, DRODLib/Stalwart.cpp, DRODLib/Station.cpp, DRODLibTests/DRODLibTest.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj.filters, DRODLibTests/src/tests/Monsters/Citizen/CitizenPuffObstacle.cpp, DRODLibTests/src/tests/Monsters/Halph/HalphPuffObstacle.cpp, DRODLibTests/src/tests/Monsters/Slayer/SlayerPuffObstacle.cpp, DRODLibTests/src/tests/Monsters/Stalwart/StalwartPuffObstacle.cpp
Citizens, Engineers, Halphs, Stalwarts, Soldiers and Slayers will now treat Puffs as obstacles, and pathfind around them. Relay Stations will also consider Puffs as obstacles when directing Citizen movement, but not when constructing pathmaps.
Some unit tests have been added to validate basic expectations of this behavior change.
Reporting thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45266
=> "Smart" monsters treat puffs as pathing obstacles

DRODLib/DbRooms.cpp
There is a break statement missing in `CDbRoom::CanPushMonster()` which leads to crashing when a puff is pushed. As this is undesirable, I have added some more break statements to make sure the code isn't dropping into cases when it shouldn't be.
=> Add missing breaks in CDbRoom::CanPushMonster()

DRODLib/Guard.cpp, DRODLibTests/DRODLibTest.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj.filters, DRODLibTests/src/tests/Monsters/ArmedMonsters/MovingIntoPuffs.cpp, DRODLibTests/src/tests/Monsters/Guard/GuardPuffObstacle.cpp, DRODLibTests/src/tests/Monsters/Slayer/SlayerPuffObstacle.cpp
To perhaps make things more consistent between human elements, Guards will now consider Puffs an obstacle. Therefore, they will not step on them, no matter what.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45266
=> Change Guards to not step on Puffs

DROD/DrodBitmapManager.cpp
Disable surface blending on images that are used for room tiles.
See thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45004
=> Disable surface blending for tile images

drodrpg/DROD/EditRoomScreen.cpp
Wires up the bits so that copying a character from one hold to another causes its default script and assets to get copied over.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45238
=> RPG: Enable support for cross-hold character copying

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbRooms.cpp
* Do not push a crate from atop another crate.
* Should be able to jump with grappling hook onto a crate (at same or lower elevation).
=> RPG: Crate logic fixes.

DRODLib/CurrentGame.cpp, DRODLibTests/src/tests/PlayerRoles/PuffPlayerRole.cpp
At some point Temporal Projections were changed so that if they had Puff appearance, they would die instantly when stepping on hot tiles. Until now, this was not implemented for the player as a puff.
=> Fatalize puff player role moving on to hot tiles

DRODLib/Guard.cpp, DRODLib/Stalwart.cpp, DRODLibTests/src/tests/Monsters/ArmedMonsters/RearmedGuards.cpp, DRODLibTests/src/tests/Monsters/ArmedMonsters/RearmedStalwarts.cpp
Changes Guards to allow them to "bump-kill" a target on an adjacent, non-open tile.
Changes Stalwarts to "bump-kill" when there is bomb on the next tile in the direction of the move, which is not dangerous when perform a "bump-kill" as the Stalwart will not move.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45432
=> Improve Guards and Stalwart with dagger

DRODLib/Clone.cpp, DRODLib/Clone.h, DRODLib/DbRooms.cpp, DRODLibTests/DRODLibTest.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj.filters, DRODLibTests/src/test-include.hpp, DRODLibTests/src/tests/PlayerRoles/ConstructPlayerRole.cpp, DRODLibTests/src/tests/PlayerRoles/FegundoPlayerRole.cpp, DRODLibTests/src/tests/PlayerRoles/PuffPlayerRole.cpp, DRODLibTests/src/tests/PlayerRoles/WaterskipperPlayerRole.cpp
The final push to make player roles work consistently between the different things that are based on players. Clones managed to slip through with a few quirks which are now corrected:
- Water dwelling clones can no longer drown
- Clones now respect the player's shallow water traversal state
- Construct and Puff clones die instantly when on Oremites or Hot Tiles respectively
- Wubba, Puff and Fegundo clones are protected from various stabs
The weird exception here is Seep, as player and player-like Seep can survive outside of walls. I'm leaving that as-is because changing it would break any rooms that use a Seep player role. It's also not a particularly difficult restriction to script if an architect wants to have it.
Related thread: …
=> Make alternate player role Clones consistent with other player-like entities

DROD/EditRoomScreen.cpp, DRODLib/DbRooms.cpp
The player shouldn't be able to enter rooms on tiles that contain Lightposts, Relay Stations or Fluff, as those are all non-open objects.
Since Lightposts are obstacles, the editor should treat them as such for the purpose of marking room edge errors.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45437
=> Make Lightpost, Relay Station and Fluff block room entry

DRODLib/DbRooms.cpp, DRODLib/Monster.h, DRODLibTests/src/tests/Elements/SquadHorn.cpp
Since Squad Horns can show up on walls and closed doors, the case exists where a Seep player can toot one. Fairly simple change.
=> Allow Squad Horn to work for Wall-based player roles

DRODLib/Briar.cpp, DRODLib/Briar.h, DRODLib/BuildUtil.cpp
Construction of briar roots didn't actually work right. `CBriars::insert()` was designed to run before briar edges are calculated, so when briar components are transferred to a newly constructed root, the edges are left disconnected. A small change was added so that if `briarEdge` contains edge data when a new root is insert, the edge data will be updated correctly.
Previously, roots would connect "correctly" due the issue fixed in #87, which was allowing briar components to connect through non-component and edge briar tiles.
The function now also takes an argument to indicate if the root is being inserted via building, so that the assert doesn't fire if roots are built onto existing briar.
=> Correctly connect briar edges when building new briar roots

drodrpg/DROD/DrodBitmapManager.cpp
It's #408 but for DROD RPG. Arguably more important since the transparency colour in RPG is eye-searing magenta.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45514
=> RPG: Disable surface blending for tile images

DROD/GameScreen.cpp
#156 removes dead monsters that are no longer used by anything. However, `CFiredCharacterCommand` may hold onto a reference to a monster that gets deleted, which can cause a crash. To fix this, monsters that get attached to these commands by `CGameScreen::PrepCustomSpeaker` should be marked as unsafe for deletion.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45552
=> Mark monster attached to CFiredCharacterCommand unsafe for deletion

DRODLib/Mimic.cpp, DRODLib/Mimic.h, DRODLib/TemporalClone.cpp, DRODLib/TemporalClone.h
Timeclones can't step onto players that are Golems or Constructs, but they can step onto other timeclones of those roles. Since monsters can generally step on Golem and Construct players, so should timeclones, if they have a step attack.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45534
=> Allow timeclones to step kill Golem/Construct players

BackEndLib/CoordStack.h, DRODLib/Slayer.cpp, DRODLib/Slayer.h
When in the door opening state, Slayers will continue to move towards broken orbs, activated one-use plates, and places that used to have something that could open a door, but now do not. This behavior is inconsistent with Halph, who will abandon missing or unusable goals. It's also doesn't make any sense.
Slayers moving to door-openers will now run `CSlayer::ConfirmGoal()`, which checks if there's something at the goal which will be useful for opening a door. If there's nothing there, the current path will be rejected.
This requires one extra function in `CCoordStack` to learn the end of the queue without removing it.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45542
=> Make Slayer abandon broken or missing orb or plate.

DRODUtil/Util3_0.cpp
Due to a vast and complex history involving typewriters, device drivers and the dubious necessity of carriage returns, different operating systems use different character combinations for indicating line endings. When I converted the `.uni` files to UTF-8, I accidently changed them from `crlf` endings to `lf` endings. git makes it difficult to change them back, and depending on your git settings files can end up with any number of line endings. It's a mess.
DROD on Windows doesn't play nicely with `lf` endings. It wants `crlf` endings. (I don't know about other platforms. We should check during the 5.2 alpha.) Since we will probably live in a world of line ending uncertainty for the foreseeable future, this presents problems.
Just fix the line endings in DRODUtil before processing the …
=> WIN32: Convert bad line ending to good ones when importing uni file

DRODLib/TemporalClone.cpp, DRODLibTests/DRODLibTest.2019.vcxproj, DRODLibTests/DRODLibTest.2019.vcxproj.filters, DRODLibTests/src/tests/TemporalToken/TemporalProjectionTunnels.cpp
When a temporal projection is trying to use a tunnel, it uses `DoesArrowPreventMovement()` to check if an arrow will stop the tunnel move. However, this function also checks the adjacent tile in the move's direction for a blocking arrow. This means that an arrow on another tile can block a tunnel move. Using `IsArrowObstacle()` instead allows only the tunnel square to be checked.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45582
=> Fix temporal clone check for tunnel moves

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h
When the player uses a "Wall Walking" or "Warp Token" accessory, they are moved. If they move onto an accessory slot, the accessory will be placed in the slot instead of being consumed. This happens because of the order that things get processed, such that the accessory is slotted before being removed.
I made it so `CCurrentGame::TeleportPlayer` can be prevented from processing the effects of a player's move. This is used in the accessory use processing to ensure the used accessory is consumed before the move is processed, preventing duplication.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=44917&page=0#441051
=> RPG: Fix accessory slot issue with teleporting accessories

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterDialogWidget.h, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CharacterCommand.cpp, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
A script command that halts execution until a given expression statisfies a comparsion to a constant value. This is useful because `Wait until var` doesn't really support that.
Additionally, adds support for complex conditional commands. See #433 for more details.
=> RPG: Add "Wait until expression" and complex conditionals script commands

drodrpg/DRODLib/Character.cpp
The `Set Var At` command should have it's variable references processed when it's copied from one hold to another. Otherwise, scripts could break!
A few tweaks were needed as `Set Var At` stores the var id in it's `w` slot.
=> RPG: Do script var merge when cross-hold copying CC_VarSetAt

DRODLib/Character.cpp
The `Set Var At` command should have it's variable references processed when it's copied from one hold to another. Otherwise, scripts could break!
A few tweaks were needed as `Set Var At` stores the var id in it's `w` slot.
=> Do script var merge when cross-hold copying CC_VarSetAt

DROD/ImageOverlayEffect.cpp
Image overlays using `DisplayTurns` use the player turn to decide when to end. However, the end turn is set based on the total turn number. Game actions that cause the turn numbers to diverge will extend the duration of image overlays incorrectly. This is a regression introduced by #228.
To fix this issue, image overlays should do all turn tracking based on the player turn.
Related thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45702
=> Track all image overlay turn counts with player turns

DRODLib/Character.cpp
`CCharacter::EvaluateLogicalOr()` incorrectly returns `false` when in the case where a nested XOR condition is true. This leads to the Or condition incorrectly evaluating to `false` when it should evaluate to `true`.
To fix, the return value for this case has been corrected.
=> Fix CC_LogicalWaitXOR case in CCharacter::EvaluateLogicalOr

DRODLib/DbXML.cpp
PR #243 reduces the memory use during hold imports by decompressing the data in chunks rather than decompressing all imported data in one go. Unfortunately, this change breaks the re-importing of saved games and demos.
When a buffer created from non-compressed data is passed into `Import_TallyRecords` or `Import_ParseRecords`, the function will hang, and possibly crash. If this happens during a hold import, any existing save and demo data for the hold will be destroyed. This is because the exit condition for the loop requires the decompression stream to exist. If a buffer has no decompression stream, the buffer containing uncompressed data will never become empty. This means the loop will keep copying the already parsed data from the import buffer into the xml parser. As this results in a …
=> Fix importing of non-compressed data in CDbXML

DROD/RoomWidget.cpp, Data/Help/1/character.html
There are some problems with custom graphics for NPCs when the NPC has a weapon:
1. If the NPC's base type is not a weapon weilding monster, it will not be drawn in the disarmed state when its weapon is surpressed. This can look bad. To fix, a small tweak has been made to character drawing to check if the NPC has a weapon, not just if the NPC base type is an armed monster.
2. The help content incorrectly describes the use of the fifth and sixth row of graphics. It says that the fifth row is for armed wading, and the sixth is for unarmed wading. This error has been corrected.
Aiming this at 5.1.1 branch since it's a minor graphical issue that can be scooped up with more major issues that need handling.
=> Fix disarmed custom graphics for weapon-having NPCs

DRODLib/Character.cpp
With the introduction of new imperatives, invisible characters can be detected by right clicking. However, `bInvisibleInspectable` and `bInvisibleCountsMoveOrder` are not set in CCharacter's constructor, and they end up being true by default.
This would cause confusion, so I have updated the constructor so they are false by default.
=> Initialize invisible character inspectability to false

DRODLib/DbRooms.cpp
As part of memory improvements (#156), invisible NPCs are killed when their script runs an end command. However, marking them as dead means they are no longer valid speakers, leading to any speech they would speak being skipped. This is a regression, as previously invisible NPCs would be able to talk, even if their script had ended.
To fix this, I changed the `KillInvisibleCharacter` function to not mark the killed NPC as dead. It is still moved to the dead monsters list, meaning it will no longer be processed, but it will retain its ability to be a speaker.
See thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45732
=> Don't mark killed invisible NPCs as dead

DROD/RoomWidget.h, DRODLib/CurrentGame.cpp, DRODLib/GameConstants.h
Moves the values for weather definitions currently in `CurrentGame.cpp` into `GameConstants.h` and updates the definitions in `RoomWidget.h` to be based on the game constant versions.
=> Consolidate weather constants

drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/GameScreen.h
In some situations, the text for the battle preview dialog can become so long that the resulting dialog becomes larger that the space it is allowed to occupy. With the additional combat information added in 1.2.8, it is now much more likely that this will occur, even when only dealing with four-figure combat damage.
An oversized dialog causes an assert to fire, and also looks bad if the dialog becomes larger than the game window. Reducing the number of entries on the dialog isn't helpful, as characters with sufficently long names can expand the dialog to the point where only one entry can fit.
To fix this, I have refactored `CGameScreen::ShowMonsterStats` by splitting the part that actually gets the monster stats and adds the image to the dialog into a new function, …
=> RPG: Fix battle preview dialog becoming too large

drodrpg/DROD/RoomWidget.cpp
The feature where all orthosquares in a room are highlighted when an orthosquare is right-clicked isn't considered helpful. It was already removed from mainline DROD. Now it will be removed from DROD RPG.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45775
=> RPG: Remove orthosquare highlighting

DROD/RoomWidget.cpp, DRODLib/Citizen.cpp, DRODLib/Citizen.h
Adds additional information when a citizen is clicked - relay stations that it has visited in the current relay cycle are marked with red shading.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=44495
=> Add shading for relay stations citizen has visited

DRODLib/DbRooms.cpp, DRODLib/Monster.cpp, DRODLib/Monster.h, DRODLib/PathMap.cpp, DRODLib/Pathmap.h, DRODLibTests/src/tests/Monsters/Construct/BrainedConstruct.cpp
There was [some discussion](https://forum.caravelgames.com/viewtopic.php?TopicID=44966&page=0#444706) on how Constructs that are brained could act. A proposal is that if no non-oremite paths are available, a Construct will move towards oremites closest to the player. This makes them seem smarter.
Implementing this was a little tricker, as it requires a secondary pathmap which can path over oremites normally to provide scores. When a semi-obstacle tile is encountered, its score is made equal to its score on the sub-pathmap multiplied by 1000.
Due to memory issues, the only way I was able to have the subpath system work was to add an option for a `CPathMap` to own another `CPathMap`, which it can pass tile mask data to, with alterations if required. Since this is only required for one …
=> Rework of Brained Construct Pathing

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/DbPackedVars.h
Due to an oversight with how setting the movement type for charactes in RPG works, characters in a saved game without a saved movement type will always become `GROUND` movers. This is wrong.
To fix this, when setting a character's members from a `CDbPackedVars`, there is now a check to see if a movement type is serialized. If there isn't one, the character will run `SetDefaultMovementType` to initialize movement.
This change required `CDbPackedVars::DoesVarExist` to be made const, which was okay since in only called const functions.
=> RPG: Fix movement default when importing from PackedVars

BackEndLib/Wchar.cpp, BackEndLib/Wchar.h, drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/Monster.h, drodrpg/DRODLib/PlayerStats.cpp, drodrpg/DRODLib/PlayerStats.h, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni, drodrpg/Texts/Stats.uni
Adds a new pre-defined var, `_MyWeakness`, that allows for scripted monsters and equipment to support additional weakness types beyond the current Goblin and Wyrm weaknesses. If the player battles a monster with a custom weakness value, and the custom weakness value of their weapon or accessory matches, the player will benefit from the x2 ATK bonus. This check is case-sensitive.
In the UI, a monster's weakness is given as its "aspect", while equipment tooltips show a "Strong against" line if a weakness is set.
Currently, a scripted entity can only have one aspect or strength, but it would be possible to use a specified character as a delimiter and support multiples.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45774
=> RPG: Add support for custom weaknesses for scripted monsters and equipment

drodrpg/DRODLib/PlayerStats.cpp, drodrpg/DRODLib/PlayerStats.h
1. If you load a pre-1.3 save, all custom scoring variables end up as as zero, due to not having default values set properly in `PlayerStats`. A new function is added that will get default values for predefined vars, and it is used for getting default values.
2. `ScriptVars::IsStringVar` has been updated to correctly return that the custom weakness var is a string.
3. Message id is missing for skeleton key score variable in the message id array, which breaks variable lookup.
=> RPG: Fix some predefined variable problems

FrontEndLib/Effect.h, FrontEndLib/TextEffect.cpp, FrontEndLib/TextEffect.h
Text effects with a duration of zero are meant to display indefinitely. However, #228 removed the effect-specific code in `CTextEffect` that made this work, and the generalized code causes zero duration text effects to never display. I've overridden the update function in `CTextEffect` to restore the intended behaviour.
Pointing at master branch since various regressions in 5.1.1 mean we probably want to release a 5.1.2 quite soon.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45817
=> Fix zero duration text effects

DRODLib/PathMap.cpp, DRODLib/Pathmap.h
Problem: If multiple room entrance tiles have the same calculated distance from a horn, the one that has priority is not well-defined. While it is deterministic, it is not reasonably predictable as to which tile would have priority.
Solutions:
1. Fix `SORTPOINT`'s less than operator function. It should provide a strict weak ordering if it is used in `std::priority_queue`, but current it does not as it is reflexive. This causes problems as it means seemingly unrelated room changes can alter the outcome of a horn's tile choice. This shouldn't break pathmap construction, as the order equally-scored tiles are evaluated in doesn't change the outcome.
2. Add a new comparison function that can be used to rank room entrances such that when there are multiple best entrances, the one chosen is …
=> Add tie-breaking for horn entrance selection

DRODLib/Character.cpp
Problem: Game crashes when a pathfinding NPC is standing on a platform and the room has pits.
Solution: Only do the platform check when the NPC is directly next to a pit tile in `CCharacter::DoesSquareContainObstacle`
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45853
See also: https://forum.caravelgames.com/viewtopic.php?TopicID=40798&page=0#403645
=> Fix pit obstacle check when NPC is on platform

DROD/GameScreen.cpp
Due to an oversight in the new face code, a custom player role that's a custom character type without a custom portrait will always show the default face during gameplay, unless the player is talking. We need to properly find the speaker type for the hold character assigned as a player role.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45024
=> Fix custom character speaker resolution when not talking

CompilingDrod_Win.md, DROD/RoomScreen.cpp, DROD/RoomScreen.h, DRODLib/GameConstants.cpp, Scripts/InstallDependencies.win32.vs2013.py
Issue was reported by Tahnan that DROD does not recognise numpad keys 8, 6, 4 and 2 when numlock is off, but the others are fine.
https://forum.caravelgames.com/viewtopic.php?TopicID=45829
At first I believed this to be an SDL2 issue, and so upgraded SDL2 and SDL2_ttf dependendencies to their latest stable versions. However, this did not seem to fix the issue. I left in the upgrade anyway, because I put in the work.
Instead, I have added functionality to recognise the arrow keys as alternative key binds for the 4 numpad keys with an issue. If you press a key and it is not initially mapped to a game command, the game will then check an alternative keybind mapping with the arrow keys and num keys flipped to see if there is then a match.
P.S. SDL2_ttf no longer uses libfreetype-6.dll so this …
=> Upgrade SDL2 and SDL2_tff and accept alternative arrow key bindings

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterDialogWidget.h, drodrpg/DROD/CharacterOptionsWidget.cpp, drodrpg/DROD/CharacterOptionsWidget.h, drodrpg/DROD/DROD.2019.vcxproj, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/drod.2019.vcxproj.filters, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h, drodrpg/DRODLib/PlayerStats.cpp, drodrpg/DRODLib/PlayerStats.h, drodrpg/DRODLib/Swordsman.cpp, drodrpg/Data/Help/1/character.html, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni, drodrpg/Texts/Stats.uni
This is a group of new scripting features for RPG.
New vars to access various game state information
`_RoomX`, `_RoomY`: The position of the current room relative to the level entrance (read-only)
`_LevelMultiplier`: Read-only access to the current level's base multiplier value
`_MyDescription`: A NPC variable to allow additional tooltip content ([Thread](https://forum.caravelgames.com/viewtopic.php?TopicID=45811))
A new NPC behaviour
`Removes Sword` - Equipment behaviour that causes the player not to have a sword. ([Thread](https://forum.caravelgames.com/viewtopic.php?TopicID=26959))
All the stuff has been plumbed in to allow NPCs to have a custom processing sequence. Doesn't effect the order equipment scripts get run because those are run in a special way.
=> RPG: Additional Scripting Features

drodrpg/DROD/SettingsScreen.cpp, drodrpg/DROD/TitleScreen.cpp, drodrpg/DROD/TitleScreen.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/SettingsKeys.cpp, drodrpg/DRODLib/SettingsKeys.h, drodrpg/Texts/MIDs.h, drodrpg/Texts/SettingsScreen.uni, drodrpg/Texts/TitleScreen.uni
Starting a new game in DROD RPG overwrites the existing game, in a non-recoverable manner. This can lead to a loss of progress if a manual save has not been created recently.
To reduce the chance of this, we can confirm if the player really wants to start a new game with a yes/no dialog. This prompt can be disabled in the settings, if the player wants.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45874
=> RPG: Add prompt when starting new game if a game is active

drodrpg/DRODLib/Character.h, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/Monster.h, drodrpg/DRODLib/MonsterFactory.h
Reworks `CDbRoom::SwitchTarstuff` so that it considers the values set for the tarstuff baby override variables. This makes it easier to integrate switcher tokens into rooms using custom tarstuff spawns.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45895
=> RPG: Also override switcher token with spawn overrides

CompilingDrod_Win.md, Scripts/InstallDependencies.win32.vs2013.py
Upgrading to later versions of the `SDL2_ttf` library causes a bunch of problems with text drawing. No one is sure how to fix it, so for now I will downgrade back to 20.0.14, which also reintroduces the `libfreetype-6` dependency.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45902
=> Downgrade SDL2_ttf version

drodrpg/DRODLib/Character.cpp
If an architect attempts to set a predefined string var to a number, the game will eventually hit an assert in `CCharacter::setPredefinedVarInt`. Instead of this, the switch statement should be broken out of for these vars.
=> RPG: Catch attempts to set string predefined vars as numbers

drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h
Ports the door to orb/plate lookup from TSS to RPG. As there are more types of door that can be connected, there is a slight difference in how door tiles are collected.
=> RPG: Add highlighting of orb/plate connected to door

DROD/GameScreen.cpp, FrontEndLib/EventHandlerWidget.cpp
Keyboard inputs are weird, and this is somehow causing some players to wait 60 turns when they do a Ctrl-Wait instead of 30 turns. This is because two input events are registered by SDL, which causes a macro'd wait command to be sent to the engine twice.
Luckily `FrontEndLib` can tell when a key event is repeated. When a repeated keypress is seen, we can increment its `repeat` value by one. Then in `CGameScreen::OnKeyDown` if we see a macro'd wait command with exactly one repeat, we do not pass it to the engine. This solves the problem.
=> Fix Ctrl-Wait sometimes waiting for 60 turns

DROD/CharacterDialogWidget.cpp, DROD/CharacterDialogWidget.h
Compared to the available screen space, the dialog for adding script commands is quite small. This can be fixed by making that dialog larger:
Since the dialog is being enlarged, the UI for variable-related commands has been rearranged, to move the value input box and increase its size. This is helpful when writing assignments using script primitives:
Behind the scenes, the third on/off listbox has been upgraded to be dynamically positioned, as its fixed position no longer worked for all commands that used it. This allowed the fourth on/off listbox to be removed, as it only existed to have a control at its specific location. (Possibly more widgets could become dynamically placed but that is outside of the scope for this PR.)
=> Enlarge Add Command dialog

drodrpg/DROD/DamagePreviewEffect.cpp, drodrpg/DROD/DamagePreviewEffect.h, drodrpg/DROD/RoomWidget.cpp
Like the enemy damage preview effect, this change adds a persisting numeric display for pending item bonuses (i.e., health, att/def gems).
=> RPG: Add item bonus preview effect.

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterOptionsWidget.cpp, drodrpg/DROD/CharacterOptionsWidget.h, drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/EditRoomWidget.h, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/SettingsScreen.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/SettingsKeys.cpp, drodrpg/DRODLib/SettingsKeys.h, drodrpg/Data/Help/1/character.html, drodrpg/Data/Help/1/editroom.html, drodrpg/Data/Help/1/settings.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/SettingsScreen.uni, drodrpg/Texts/Speech.uni
Three somewhat related features packaged together:
A new setting to make show NPC's in-game appearance the default. When this is active, holding the Alt key will show the generic editor appearance. It can also be toggled in-editor with the F6 key. ([Thread](https://forum.caravelgames.com/viewtopic.php?TopicID=45910))
To help the above, the `_MyColor` variable can now be preset in the character options dialog. When this is done, the character's altered color can be seen when previewing NPC appearances.
Finally, inputs have been added to the character options dialog to set a custom speech color. The three RGB values are set separately, then combined into a single value for storage. This is because it was the method I was able to get working. …
=> RPG: Additional character customisation utilities

drodrpg/DRODUtil/Util3_0.cpp
This is #440 for the RPG version of DRODUtil. As before the conversion is only done for WIN32 builds, but if it was discovered that the problem exists on other platforms, a similar fix can be made.
=> RPG WIN32: Convert bad line ending to good ones when importing uni file

drodrpg/DRODLib/Combat.cpp
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45916
=> RPG: Make each attack/defend trigger for all equipment types

drodrpg/DRODLib/Character.cpp
The processing sequence was being used as the fallback value instead of the character's existing color value.
=> RPG: Fix color getting in CCharacter::ResolveLogicalIdentity

drodrpg/DRODLib/Swordsman.cpp
A few improvements to the quick travel to room edge algorithm:
- Allow pathing over water if the player can move on water
- Allow pathing over pits if the player can move on pits
- Remove logic that treats closed doors as always passable for flying player.
=> RPG: Improve quick travel logic

DRODLib/DbRooms.cpp
Due to 5.2 changes, importing a hold that contains a character crashes the game.
This happens in `CDbRoom::ClearMonsters`. Due to the addition of character behaviors allow characters to be monster targets, characters with these behaviors need to be removed from the monster enemy list when deleted. This requires the `CMonster` pointer to the character to be cast to `CCharacter` to check for these behaviors. Due to the particulars of how monsters are imported, this cast fails during importing, and the game crashes when trying to access an invalid pointer.
This can be avoided by checking if the room is attached to a game. Characters cannot gain behaviors until their game is set, and this does not happen during importing. Therefore, the check for monster target behaviors can be safely …
=> Fix import crash when deleting character

FrontEndLib/SubtitleEffect.cpp, FrontEndLib/SubtitleEffect.h
Without this fix, room lock indicator will disappear when effects are updated.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45938
=> Fix display of subtitle with text duration of zero

DRODLib/Slayer.cpp
Due to how orb data is managed, Slayer should check if a targeted orb or plate is still the correct tile type for that target.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45542
=> Add check for changed orb/plate tile in CSlayer::ConfirmGoal

DRODLib/Character.cpp
Pathfinding characters will not recalculate their paths unless they become invalid, or their goal square changes. This causes unintuitive behaviour when using the Single Step option.
For better and less confusing behaviour, if the `Move To` command is in single step mode, it will make the pathing goal invalid after the movement has been calculated, ensure that subsequent calls will require a new path to be calculated.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45917
=> Reset character pathing goal after single step move to

BackEndLib/Wchar.cpp, BackEndLib/Wchar.h, drodrpg/DROD/DROD.2019.vcxproj, drodrpg/DROD/EquipmentDescription.cpp, drodrpg/DROD/EquipmentDescription.h, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/drod.2019.vcxproj.filters
Changes to improve the tooltip for in-room equipment tiles:
- Equipment properties are now shown in addition to stat changes
- When applicable, both ATK and DEF changes are shown, for all equipment types
- As both stat changes are shown, the stat type is shown in the tooltip.
This required some refactoring to create common code for describing equipment. For lack of a better place, a new class `EquipmentDescription` has been created, which holds functions to create these strings. There are functions to construct the strings for predefined equipment, and a function for custom equipment. For equipment types that can have multiple properties, a separator can be specified, allowing the function to used for both in-room tooltips and in the side panel.
Thread: …
=> RPG: Improve tile description for equipment

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DRODLib/Character.cpp
Couple of fixes in places with script command switch statements:
- Added `SetVarAt` to `CCharacter::RotateClockwise`
- Readded cases that were lost in `CCharacterDialogWidget::PrettyPrintCommands` due to dodgy copy-paste.
=> RPG: Fix missing and bad script command cases

drodrpg/DROD/SettingsScreen.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/GameConstants.cpp, drodrpg/DRODLib/GameConstants.h, drodrpg/Data/Help/1/script.html
Numpad controls are not expanded into the correct strings when using the predefined control vars. They require special handling. This handling exists in `SettingsScreen.cpp`, and has been moved to `GameConstants` to make it available in other places.
The predefined control vars have also been added to the script help files.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45962
=> RPG: Fix numpad controls not being correctly expanded

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
Similar to the TSS 5.2 imperative in concept, this allows non-visible characters to appear in a square's right-click tooltip. The character's custom description is also included.
Internally, this is a separate step from adding a monster's information to the tooltip. Most of the monster information is not applicable to an invisible character, and it is possible for multiple invisible characters to share a tile.
=> RPG: Invisible Inspectable imperative

drodrpg/DRODLib/Character.cpp, drodrpg/Data/Help/1/script.html
Allows the use of expanded variables in autosave names. This functions as it does in speech and other text locations.
Related post: http://forum.caravelgames.com/viewtopic.php?TopicID=32862&page=0#441140
=> RPG: Allow use of variable expansion in autosave names

DRODLib/Character.cpp, DRODLib/Clone.cpp, DRODLib/Monster.cpp, DRODLib/PlayerDouble.cpp, DRODLib/TemporalClone.cpp, DRODLib/Weapons.h
#421 changed clones to work more like the entities they are based on. However, due to an oversight with the way hot tile damage works, it caused Wubba clones to become immune to hot tiles.
Fixing this requires the addition of a new weapon type to represent hot tile damage (which already exists in 5.2). This allows checks for hot tile damage to be performed in `CClone::OnStabbed`.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45964
=> Fix wubba clone hot tile damage

DROD/RoomWidget.cpp
If the `_Weather` var is used to change if a room is outside, the room will require a full redraw to account for cloud shadows and sky reflections in water.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=44130
=> Redraw room when outside state is changed

DROD/ImageOverlayEffect.cpp, DROD/ImageOverlayEffect.h, DRODLib/CharacterCommand.cpp, DRODLib/CharacterCommand.h, Data/Help/1/script.html
Adds support for two additional Image Overlay commands, `TileGrid` and `Repeat`. A fix for the `Jitter` command is also included.
`TileGrid x y` copies the image to create an x by y grid of the image. This is placed onto a new surface, `pTiledSurface`, as positioning of a tiled image is different than for other altered images. Images that have been rotated cannot be tiled, as the current way rotation is applied to images leads to very poor results when tiling.
Example of tiled image:
`Repeat r x y` copies the final image r times, with an offset of x,y applied on each repetition. The offsets can be positive or negative, allowing for repetition in all directions. This works with all image alterations, and repetitions that go outside the boundary of a room are clipped appropriately.
Example …
=> Add TileGrid and Repeat image overlay commands

DRODLib/CurrentGame.cpp
When fegundo ashes would generated over a pit by `CCurrentGame::FegundoToAsh`, they are not, and an `ObjectFell` event is created. A weapon type can be specified for falling objects, but the wrong type is given for ashes created this way. A value of -2 for "no weapon" should be used, or a sword will be drawn falling alongside the ashes.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45973
=> Use correct weapon type in Fegundo ashes ObjectFell event

DROD/RoomWidget.cpp
`nCustomColor` needs to be included in the copy constructor for `TileImageBlitParams`, as currently it will end up with junk values when the object is copied. The most immediate symptom of this is that it causes weapons to flash random colours.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45957
=> Initialize nCustomColor in TileImageBlitParams copy constructor

DRODLib/DbXML.cpp
The import buffer is not explicitly reinitialized after records are parsed in `CDbXML`. This can cause a strange issue where if the user is asked to confirm an import, the import will succeed at doing nothing, as the game thinks there is nothing to import, even if the buffer still has data. We should do the reinitialization in the buffer version of `ImportXML`.
In some situations, hold importing will end with in a successful state due to the import buffer not having compressed data. However, it can be the case that some import data remains in the buffer, and will not be cleared. To prevent this, mark the import as complete in this situation.
Thread(?): https://forum.caravelgames.com/viewtopic.php?TopicID=45985
=> Improve safety when importing data

DROD/RoomWidget.cpp, DRODLib/Character.cpp, DRODLib/Character.h
#452 tweaked character drawing to improve support for giving weapons to characters with a non-armed base type. However, it turns out this breaks animation for charaters with zero animation speed.
A more robust check has been added to ensure the swordless frame is only used for a character that 1) has a weapon, either through its base type or setting one using `_MyWeapon` and 2) does not have its weapon active, due to it being turned off or sheathed.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45989
=> Fix zero-speed characters animation

DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, DRODLib/DbRooms.cpp
Since stepping on master walls and hold complete walls invalidates a room demo, it would be helpful to have a way to avoid that. Room lock already exists to prevent unfortunate moves, so it can be expanded to prevent more of them.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=34068
=> Block player movement onto master and win walls when room lock is active

DRODLib/Character.cpp, DRODLib/Monster.cpp
If a character has the `MIQ_PathfindOpenOnly` movement type, and no move is available, `CCharacter::GetMovement` will not set values for the `dxFirst` and `dyFirst` arguments. These then get used to try to set an orientation, which ends up being invalid. When the character is next drawn, the game will crash.
To fix, `dxFirst` and `dyFirst` should be set to zero in the no-move case for pathfinding. Additionally, I have tweaked `CMonster::SetOrientation` so that it will not set `wO` to an invalid orientation. This should mean that any future incidents have less catastrophic results.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45994
=> Fix bad character orientation due to no pathfinding move

DROD/CharacterDialogWidget.cpp, DRODLib/Character.cpp, DRODLib/CharacterCommand.h, DRODLib/DbBase.cpp, Data/Help/1/script.html, Texts/MIDs.h, Texts/Speech.uni
Simple command that sets the value of all _Myscript variables to `NO_OVERRIDE`. Makes things easier for scripters and is probably faster than using `Set Var`.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45934
=> Add script command to reset _MyScript variables

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterDialogWidget.h
`CCharacterDialogWidget::ExtractCommandIndent` was always acting on the main command list, even when editing a default script. This meant it would crash during a Ctrl-B copy if the default script being worked on was long than the script in the main command list.
To fix this, the function has been updated to take a command list as an argument, along with `CCharacterDialogWidget::toText`.
=> RPG: Fix crash in CCharacterDialogWidget::ExtractCommandIndent

DRODLib/DbXML.cpp
Made the minimal change, though it is probably more correct to fix the declarations for the other values on the lines.
=> cast to match integer type

DROD/CharacterDialogWidget.cpp, DROD/CharacterOptionsWidget.cpp, DROD/CharacterOptionsWidget.h, DROD/RoomWidget.cpp, DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/DbBase.cpp, DRODLib/DbHolds.cpp, DRODLib/DbRooms.cpp, Data/Help/1/character.html, Texts/MIDs.h, Texts/Speech.uni
Adds the ability to change a character's speech color, in the same way it was added to RPG 1.3 in #500.
=> Add support for custom speech color

.gitmodules, Scripts/InstallDependencies.win32.vs2013.py
This PR adds the [Caravel fork](https://github.com/CaravelGames/metakit) of metakit as a submodule of the repository. Additionally, it updates the Windows dependency script to fetch a pre-built version of the metakit library, which matches the previous metakit that was being fetched and built.
See #545 for why this has been done. In short, metakit repos have a tendency to be unreliable.
=> Add metakit as a submodule

DRODLib/Character.cpp
It turns out the crash fixed in #544 was also covering up a regression, where If behaviour on `Move To` no longer worked if the character uses a pathfinding imperative.
This is a regression in 5.1.1, so the PR is pointed at the master branch.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45994
=> Fix Move To if logic when character has pathfinding

drodrpg/DROD/GameScreen.cpp
`CGameScreen::ReattachRetainedSubtitles()` tries to reattach subtitles to things after an undo. However, if the subtitle was attached to an entity that was generated by a script, it handles it poorly. The effect is deleted, which later causes a crash if a pointer to it exists elsewhere.
DROD 5.2 doesn't have this issues, so I've copied over the code from there to RPG to fix the problem.
=> RPG: Fix crash when trying to reattach subtitle

drodrpg/DROD/RoomWidget.cpp
Currently, the right-click tooltip does not show the "plain" floor types. While they usually do not have game logic associated with them, it is possible for character scripts to treat them as logically different.
Noting these floor types can therefore be useful. It also gives a conformation that a tile contains no functional floor types that may be obscured by monsters or items.
=> RPG: Include plain floor types in right-click subtitle

drodrpg/DROD/RoomWidget.cpp
Moving away from a room edge using a tunnel can lead to an assert, as the player's sword may be drawn outside of the room during movement animation.
To fix, clipping should be applied to the sword blit in the case when the player is being animated, and their previous sword position is outside of the room.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45844
=> RPG: Clip sword blit when its previous location is outside room

drodrpg/DRODLib/Monster.cpp
It was noticed that previously, the default damage for Aumtlich beams was rounded down if the player had an odd HP value, but the change to support customising the damage caused it be rounded up. This could have undesirable effects on existing level sets, so a special case has been added to preserve the old behaviour for beams halfing HP.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45830
=> RPG: Preserve old behaviour for 50 percent damage beam

CompilingDrod_Win_MSVS2013.md, FrontEndLib/FontManager.cpp, Scripts/InstallDependencies.win32.vs2013.py, readme.md
Recent discoveries make it possible to update the development branches to version `2.20.1` of SDL_ttf. A code fix is required, along with a change to one font file. This solves issues that occured during a previous upgrade attempt.
The first issue was that text outlines became displaced. This is probably due to a fix in version of `2.0.15` SDL_ttf related to outline positions. `CFontManager::RenderWord` appears to contain a work around for this problem, which has been removed as it is no longer needed.
The second issue is that some text was displaced, and text in the title menu was cut-off. This is due to a fix in the freetype library, where it began respecting the `useTypoMetrics` flag present in TrueType fonts. The version of the Tom's New Roman font included with DROD had this flag …
=> Update SDL_ttf to version 2.20.1

CompilingDrod_Win_MSVS2013.md, FrontEndLib/FontManager.cpp, Scripts/InstallDependencies.win32.vs2013.py, readme.md
#558 but for the RPG development branch. This updates SDL_ttf to version `2.20.1`, and makes a change in `CFontManager::RenderWord` to fix the drawing of text outlines. See the other PR for much more detail.
The one difference between DROD and DROD RPG is that RPG installations are already using a later version of the Tom's New Roman font, which does not have issues with later versions of freetype.
=> RPG: Update SDL_ttf to version 2.20.1

drodrpg/DROD/EquipmentDescription.cpp, drodrpg/DRODLib/Combat.cpp, drodrpg/DRODLib/Combat.h, drodrpg/Data/Help/1/script.html
Makes weakness behaviours and `_MyWeakness` functional on shield items. The player's effective defense is doubled against monsters their shield is strong against (unless that monster has `No enemy defense`). This applies during combat, and when taking damage from monsters that attack outside of combat.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46014
=> RPG: Make shields provide doubled DEF against weak monsters

DROD/CharacterDialogWidget.cpp, DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/CharacterCommand.h, DRODLib/DbBase.cpp, DRODLib/DbRooms.cpp, DRODLib/DbRooms.h, Data/Help/1/script.html, Texts/MIDs.h, Texts/Speech.uni
Script commands for counting the amount of things in a room region.
This required a bit of refactoring for the tile counting command, shifting the actual check for a square into the new `CDbRoom::DoesSquareContainTile`. As a side effect, this fixes a bug where variant orbs and plates would not be seen by `Wait for Item` in certain situations.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46007
=> Count entity type and Count item script commands

CompilingDrod_Win_MSVS2013.md, FrontEndLib/FontManager.cpp, Scripts/InstallDependencies.win32.vs2013.py, readme.md
Changes for updating SDL_ttf to `2.20.1` for the master branch. (See #558 and #559)
=> Update SDL_ttf to version 2.20.1 for master branch

DRODLib/Character.cpp, DRODLib/Construct.cpp, DRODLib/CurrentGame.cpp, DRODLib/Mimic.cpp, DRODLib/Monster.cpp, DRODLib/Monster.h, DRODLibTests/src/tests/Scripting/ImperativePushable/PushableByBody.cpp
If a falling tile such as a trapdoor drops by having an monster pushed off of it, it is possible for the pushing entity to end up on an otherwise impassable pit or water tile. This is inconsistent with other situations where a tile is altered to pit or water beneath an entity, which can lead to them dropping or drowning.
To fix, monsters now set a flag `bPushedOtherMonster` when they body push a monster. If this flag is set after their movement is processed, monsters that can push other monsters will call `CDbRoom::CheckForFallingAt` at their new position. This will cause them to drop if their destination tile is unsuitable. `CCurrentGame::ProcessPlayer` has had a similar change made to allow the same for player movement.
=> Fix interaction when pushing character off of falling tile

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterDialogWidget.h, drodrpg/DROD/DROD.2019.vcxproj, drodrpg/DROD/DemoScreen.cpp, drodrpg/DROD/DemosScreen.cpp, drodrpg/DROD/DrodEffect.h, drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/DrodScreen.h, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/GameScreen.h, drodrpg/DROD/HoldSelectScreen.cpp, drodrpg/DROD/ImageOverlayEffect.cpp, drodrpg/DROD/ImageOverlayEffect.h, drodrpg/DROD/RestoreScreen.cpp, drodrpg/DROD/RoomEffectList.cpp, drodrpg/DROD/RoomEffectList.h, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DROD/drod.2019.vcxproj.filters, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CharacterCommand.cpp, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/CueEvents.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
Adds support for Image overlays to RPG. The effect code is taken from the 5.2 dev branch in order to include the new image overlay commands.
All the wiring should be included, although it does touch a lot of places so it's possible I missed something.
=> RPG: Add Image overlay script command

drodrpg/DROD/EditRoomScreen.cpp
Items that come in various sizes take up a lot of editor space. To save space, these items can be combined into a single icon in the item panel which can be scrolled through.
Dirt blocks, ATK upgrades, DEF upgrades and Health pickups have each been collated. Additionally, ATK and DEF now have linked scrolling. The T-layer tab has been rearranged for the new groupings.
=> RPG: Collate various editor items

DROD/ImageOverlayEffect.cpp, DROD/ImageOverlayEffect.h, DRODLib/CharacterCommand.cpp, DRODLib/CharacterCommand.h, Data/Help/1/script.html
Adds two new image overlay commands, `TimeLimit` and `TurnLimit`, that place a restriction on how long an image overlay can live for.
`TimeLimit` causes the overlay to end after the specified amount of time. Primarily useful for capping the length of dynamic effects where it may be difficult to otherwise set the duration.
`TurnLimit` causes the overlay to end after the specified number of turns pass. Useful for placing a turn limit on an effect that loops forever, in a way that is self-contained.
=> Add commands to cap image overlay duration

drodrpg/DROD/ImageOverlayEffect.cpp, drodrpg/DROD/ImageOverlayEffect.h, drodrpg/DRODLib/CharacterCommand.cpp, drodrpg/DRODLib/CharacterCommand.h, drodrpg/Data/Help/1/script.html
Adds the `TimeLimit` and `TurnLimit` image overlay commands to DROD RPG. See #573 for details.
=> RPG: Add commands to cap image overlay duration

drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/PendingPlotEffect.cpp, drodrpg/DROD/PendingPlotEffect.h, drodrpg/DRODLib/TileConstants.h
A few fixes/improvements for editing in RPG:
- Removes the automatic placement of walls around stairs, to match the change in TSS.
- Adds the ability to cover fuses and mist with mirrors and crates in the editor.
- Fixes automatic NPC previewing when an object menu is open. Previously, previewing required animation to be active, which was blocked when an object menu was opened. The code has been tweaked to allow preview even when animation is not happening. (thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45910)
=> RPG: Improve editor functionality

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DROD/TileImageCalcs.cpp, drodrpg/DROD/TileImageCalcs.h, drodrpg/DROD/TileImageConstants.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h, drodrpg/DRODLib/TileConstants.h, drodrpg/Texts/EditScreens.uni, drodrpg/Texts/MIDs.h
Adds a new tile that generates and expands mist after a monster is battled. A vent with no T-layer item on its square will create a single tile of mist at its location. A vent with mist already on it will expand all connect mist. If multiple vents are attached to a group of connect mist tiles, only one expansion occurs.
There are a few mist-specific methods added, to support mist being able to connect via covered tiles.
This PR also includes a fix for mist drawing when new mist tiles are plotted diagonally adjacent to existing mist.
=> RPG: Add mist vent

DROD/RoomScreen.cpp, DROD/RoomScreen.h
During a merge between `tss-5.2-dev` and `master`, the fix from #483 got clobbered by the changes to support more rebindable keys. Since the underlying problem is still there, I've ported the fix to work with the new keybinding system.
=> Restore fix to accept alternative arrow key bindings

drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/EditRoomScreen.h
A few issues have seeped into the editor during some changes. This problems should now be fixed:
- Some stair creation code was still working as if the staircase would be lined with walls.
- Removing a staircase was still removing adjoining walls.
- Removing arrows would not remove orb associations when appropriate.
Additionally, a removed staircase will now be replaced with the most recently select floor type.
=> RPG: Fix some editor issues

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/DbPackedVars.cpp, drodrpg/DRODLib/DbPackedVars.h
When an empty default script is serialized, both values saved to `ExtraVars` are skipped if the script is empty. This causes a problem when all commands are removed from a default script, as the change will not be saved.
To avoid this problem, we can always save the script size, and unset the packed command buffer if no commands are in the script when saving.
=> RPG: Fix bad save of empty default script

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/EquipmentDescription.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DROD/TileImageCalcs.cpp, drodrpg/DROD/TileImageConstants.h, drodrpg/DRODLib/BuildUtil.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h, drodrpg/DRODLib/GameConstants.cpp, drodrpg/DRODLib/Mimic.cpp, drodrpg/DRODLib/Monster.cpp, drodrpg/DRODLib/Monster.h, drodrpg/DRODLib/Swordsman.cpp, drodrpg/DRODLib/TileConstants.h, drodrpg/Data/Help/1/script.html, drodrpg/Texts/EditScreens.uni, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
Ports the powder keg element to DROD RPG, along with the changes to explosion processing to make that possible. Additional, a new script behavior has been added that can prevent a player or character's sword from detonating explosive objects, and an "explosive safe" weapon is able to push kegs.
=> RPG: Add powder keg element

DROD/CharacterDialogWidget.cpp, DROD/CharacterDialogWidget.h, DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/CharacterCommand.cpp, DRODLib/CharacterCommand.h, DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, DRODLib/DbBase.cpp, DRODLib/DbHolds.cpp, DRODLib/DbHolds.h, DRODLib/DbSavedGames.cpp, DRODLib/DbSavedGames.h, DRODLib/PlayerStats.cpp, DRODLib/PlayerStats.h, Data/Help/1/myscript.html, Data/Help/1/script.html, Data/Help/1/scriptarray.html, FrontEndLib/ListBoxWidget.cpp, Texts/MIDs.h, Texts/Speech.uni
Adds new functionality to scripts by allowing arrays. A script variable starting with a `#` becomes a global array, and a variable starting with a `@` becomes a local variable. To avoid weird issues with serialization, once a variable is created, it can't be renamed in a way that changes its "arrayness".
Internally, arrays are technically maps, as they can be non-continuous. Negative indexes are also supported, although this is not unheard of in some languages.
Global arrays are serialized back to the packed stats object when saving. The number of active items in the array is saved as the first value, followed by a sequence of key/value pairs. The `readBpUINT` and `writeBpUINT` functions have been moved to `CDbSavedGame` to allow them to reused for this. To save space, values of zero are …
=> Add support for array script variables

DRODLib/CurrentGame.cpp
If a non-visible character runs an `End` command after the player answers a question, the script does not correctly end. This is because post-question processing does not check if the script has been ended. Previously this would get picked up by the next monster processing pass, but changes to how characters are managed means this doesn't happen.
To fix this, a script end check has been added to answer processing.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46140
=> Check script completion after question answer processing

DRODLib/DbBase.cpp, Texts/DemosMessages.uni
It's not certain that the player who records a demo is "he". In this situation, singular "they" can be used instead. Messages updated in both text files and `DbBase`.
=> Update demo description strings

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CueEvents.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/Monster.cpp, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
Makes crates do a few extra things:
- Standing on a crate will prevent the effect of oremites and hot tiles
- Crates will be destroyed by fire traps
=> RPG: Add more tile + crate interactions

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/PlayerStats.cpp, drodrpg/DRODLib/PlayerStats.h, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Stats.uni
Adds script vars `_TotalATK` and `_TotalDEF`, which allow access to the values calculated in `CCurrentGame::getPlayerATK` and `CCurrentGame::getPlayerDEF`.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46091
=> RPG: Add script vars to access total player ATK and DEF

DROD/Main.cpp
Currently, some preprocessor blocks are set up so that exception catching and logging is mutually exclusive with functionality provided by the `_DEBUG` flag, such as assert logging. This makes it more difficult to assess certain crashes, as they do not trip any asserts before breaking everything. By allowing exceptions to also be caught and logged, more information might be collected to help with such problems.
=> Allow exception catching in _DEBUG builds

DROD/CharacterDialogWidget.cpp, DRODLib/Character.cpp, DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, DRODLib/DbBase.cpp, DRODLib/PlayerStats.cpp, DRODLib/PlayerStats.h, Data/Help/1/script.html, Texts/MIDs.h, Texts/Stats.uni
New script vars to access some more bits of information:
- `_PlayerWeapon` gives access to the player's base weapon, allowing to be checked separately from the currently wielded weapon, and provides another way to change it, include enabling and disabling the weapon.
- `PlayerLocalWeapon` gives access to the weapon the player is currently wielding, allowing scripted changes of the local weapon without effecting the global weapon, including arming and disarming.
- `_Input` give read-only access to the most recent command the player input.
- `_InputDirection` gives read-only access to the movement direction of the most recent player input, or 4 if a non-movement command was input.
The two input commands required a new member variable in `CCurrentGame`, which is set by `ProcessCommand`. It …
=> Add script vars to access player weapon and inputs

DROD/VarMonitorEffect.cpp, DROD/VarMonitorEffect.h, DRODLib/Character.cpp, DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, DRODLib/PlayerStats.cpp, DRODLib/PlayerStats.h, Data/Help/1/scriptarray.html
Some changes to improve array vars:
1. Limited array indexes to be between -50,000 and 50,000 inclusive. Mainly an improvement for avoiding issues with supermassive arrays.
2. Added tracking of array vars to the var monitor effect. It does a bit of trickery to allow existing infrastructure to be reused, but it works well enough.
=> Improvements for array script variables

drodrpg/DRODLib/Character.cpp
When you have a character with Evil Eye or Mad Eye as its base and it is attacking via Attacks in Front, it will now emit the Evil Eye Woke event to trigger the HMMM sound effect.
This also means you can now use this event in script logic in this case. This has the potential to mess up scripts in previously released holds, but I am not aware of any that have rooms that fulfill all three of these criteria at the same time:
- contains default eye monster
- contains character eye
- waited for this event
I believe this should be safe.
=> RPG: Character emits Evil Eye Woke

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/Monster.cpp
When using Turn Into Monster command on a character, if the base monster class had no orientation, it would set the orientation to NW, which would then spam errors when trying to draw this orientation.
This PR ports over a fix for this that's in classic DROD.
=> RPG: Port fixes for Turn Into Monster orientation

drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/ParticleExplosionEffect.h, drodrpg/DROD/TarStabEffect.cpp, drodrpg/DROD/TarStabEffect.h, drodrpg/DRODLib/MonsterFactory.cpp
Adds the two new monsters to the monster editor tab. In order to fit them I had to shrink the serpents from 2 tiles wide to one. It was either those or the rock giant, but reducing the serpents to only the head looked better.
Also adds effects to combat with the puff, wiring up its death effect and replacing blood with fluff particles. The construct still bleeds, that's a change for another day.
=> RPG: Add new monsters to editor + puff effects

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/DrodEffect.h, drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/DrodSound.cpp, drodrpg/DROD/DrodSound.h, drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/Main.cpp, drodrpg/DRODLib/CueEvents.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/Monster.cpp, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
Add event for queen spawns which you can now wait for etc.
New egg spawn event plays egg spawning sound.
Add construct death sounds.
Add golem debris effect instead of blood when fighting construct (I thought it had its own effect in classic DROD, but turns out it doesn't)
Has an accompanying PR in the data repo.
=> New noises for egg spawns and Construct splat

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Monster.cpp
Mist was incorrectly blocking moving characters and egg spawns. This fixes both of these.
=> RPG: Fix mist blocking character movement and egg spawns

drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h
The default Seep monster fades in and out. This change makes all characters with wall movement type also fade in and out. I wanted my custom seep enemies to exhibit this behavior, which was not possible to set before.
This isn't fully backwards compatible as characters with a Seep identity by default have wall movement, so any custom seep characters in published holds will now fade in and out where they didn't before. This can be disabled by giving those characters any other movement type (this being customizable is new 1.3 functionality), so if necessary holds can be updated to bring the visuals back to how they were before.
The alternative is to stop making characters with a seep identity have wall movement by default and require the player to set it themselves. No published hold had …
=> RPG: Make wall movement characters transparent

drodrpg/DRODLib/Character.cpp
https://forum.caravelgames.com/viewtopic.php?TopicID=40625
Game could desync when changing an NPC appearance, this ports over a fix from classic DROD. Looking at the fix, this bug may have been present for changing player roles too.
=> RPG: Port fix for desync when changing monster appearance

drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/EditRoomWidget.h
In #613  I changed the interface of DrawCharacter. As EditRoomWidget inherits from RoomWidget, Draw Character was no longer being called in the editor for non-visible characters. This updates the interface to match.
=> RPG: Fix regression with non-visible characters in editor

drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h
Second attempt at fixing https://forum.caravelgames.com/viewtopic.php?TopicID=40625
When you undo a room and reload it, the monster list wasn't populating from the explored room, but rather the freshly reloaded room. This caused an issue if a monster had previously used the Set Appearance command, as they have different script commands compared to their logical identity, and so their script commands are only in the explored room monster list.
This creates a variant of the GetCharacterFromScriptId method to pull from the provided explored room.
=> RPG: Fix characters restoring from wrong room when undoing

FrontEndLib/ListBoxWidget.cpp, drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterDialogWidget.h, drodrpg/DROD/VarMonitorEffect.cpp, drodrpg/DROD/VarMonitorEffect.h, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CharacterCommand.cpp, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbHolds.cpp, drodrpg/DRODLib/DbHolds.h, drodrpg/DRODLib/DbSavedGames.cpp, drodrpg/DRODLib/DbSavedGames.h, drodrpg/DRODLib/PlayerStats.cpp, drodrpg/DRODLib/PlayerStats.h, drodrpg/Data/Help/1/script.html, drodrpg/Data/Help/1/scriptarray.html, drodrpg/Texts/MIDs.h
Adds new functionality to scripts by allowing arrays. A script variable starting with a `#` becomes an array. To avoid weird issues with serialization, once a variable is created, it can't be renamed in a way that changes its "arrayness".
Internally, arrays are technically maps, as they can be non-continuous. Negative indexes are also supported, although this is not unheard of in some languages.
Arrays are serialized back to the packed stats object when saving. The number of active items in the array is saved as the first value, followed by a sequence of key/value pairs. The `readBpUINT` and `writeBpUINT` functions have been moved to `CDbSavedGame` to allow them to reused for this. To save space, values of zero are not packed when serializing (as getting an int value from a map will …
=> RPG: Add support for array script variables

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h
Third attempt at fixing https://forum.caravelgames.com/viewtopic.php?TopicID=40625
Undoes PR #616 , which was working around the real issue and broke all saved games. Characters now store their initial identity, which stays the same even after using Set Appearance. When recovering default character scripts, the initial identity is used. If the initial identity does not exist (because you're loading an old saved game, etc.) then the current identity is assumed.
=> RPG: Fix Set Appearance for the third time

DROD/CharacterDialogWidget.cpp, DROD/CharacterDialogWidget.h, DRODLib/Character.cpp, Data/Help/1/myscript.html
A few changes to some script commands:
- Remove `MyScriptF` overrides for the `Wait for item group` commands, as like imperatives and behaviors, the numeric values of item groups aren't attached to any kind of game logic
- Added information about `Wait for item group`'s other myscript overrides to the help files
- Added a new UI widget to allow multi-tile monsters to be selected in `Wait for entity` and related commands
- Fixed a problem where `CCharacter::CountEntityType` could count the same multi-tile monster more than once
=> Script command tweaks

DROD/GameScreen.cpp
Removing spark effects in `CGameScreen::ProcessCueEventsBeforeRoomDraw` after `CCurrentGame` has loaded a new room can lead to crashes. To fix this, the spark clearing is skipped if the player has left the room.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=46021
=> Don't clear spark effects when in process of leaving room

DROD/CharacterDialogWidget.cpp, DROD/CharacterDialogWidget.h, DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/CharacterCommand.h, DRODLib/CurrentGame.cpp, DRODLib/DbBase.cpp, DRODLib/DbRooms.cpp, DRODLib/DbRooms.h, DRODLib/PlayerStats.cpp, DRODLib/PlayerStats.h, DRODLibTests/src/tests/Monsters/Guard/GuardPuffObstacle.cpp, Data/Help/1/myscript.html, Data/Help/1/script.html, Texts/MIDs.h, Texts/Speech.uni, Texts/Stats.uni
A loesely related group of additions to allow more stuff to be queried in scripts.
- `_MonsterSize` script primitive, to check how large a monster at a specific tile is. Works on both heads and pieces.
- `_CleanRooms` script primitive, which can be used to know how many rooms in the level are clean. Parameter can be used to filter the types of rooms checked for (Required/secret/unrequired).
- Added a "Required" option to `Wait for entity`. This looks for required monsters. ([Thread](https://forum.caravelgames.com/viewtopic.php?TopicID=38994))
- `Wait for player state`, which allows checking for invisibility, haste and poweredness.
- `_Combo` predefined var, which accesses the combo number.
(A few unused variable declarations were also trimmed)
=> More script queries

BackEndLib/Date.cpp, BackEndLib/Date.h, DROD/DemosScreen.cpp, DROD/DemosScreen.h, DROD/DrodScreen.cpp, DROD/DrodScreen.h, DROD/HoldSelectScreen.cpp, DROD/HoldSelectScreen.h, DROD/RestoreScreen.cpp, DROD/SelectPlayerScreen.cpp, DROD/SettingsScreen.cpp, DRODLib/DbBase.cpp, DRODLib/SettingsKeys.cpp, DRODLib/SettingsKeys.h, Data/Help/1/restore.html, Data/Help/1/settings.html, Texts/MIDs.h, Texts/RestoreScreen.uni, Texts/SettingsScreen.uni
A bundle of changes to improve somethings around demos and saves:
- Added a button to the restore screen to export saves for the current hold. To do this, the save export code was moved to a new function, `CDrodScreen::ExportSaves`, which can be flagged to filter to a single hold before doing the export. ([Thread](https://forum.caravelgames.com/viewtopic.php?TopicID=45202))
- Changed how exported demo files are named if they contain multiple demos. The hold and level name are used, along with the number of demos that will be exported, ([Thread](https://forum.caravelgames.com/viewtopic.php?TopicID=45978))
- Added an option to activate/deactive playing demos on the hold management screen ([Thread](https://forum.caravelgames.com/viewtopic.php?TopicID=40769))
- Added an option to change the …
=> Improvements for demo management and save exports

DROD/CharacterDialogWidget.cpp, DROD/RoomWidget.cpp, DRODLib/Character.cpp, DRODLib/CharacterCommand.h, DRODLib/CurrentGame.cpp, DRODLib/CurrentGame.h, DRODLib/DbBase.cpp, DRODLib/DbRooms.cpp, DRODLib/MonsterType.h, Data/Help/1/script.html, Texts/MIDs.h, Texts/Speech.uni
Add a new command, `Select square`, that enables the user to input a room tile, which is then stored in the `_ReturnX` and `_ReturnY` vars.
This works by hooking into the double placement command, using two new monster pseudo-types. One allows any square to be selected, while the other retains the normal double placement restrictions. The command will wait if a double is already being placed, since only one thing can use the square selection input at once.
=> Add script command to prompt tile selection

drodrpg/DRODLib/DbRooms.cpp
Tendry would fall asleep in rooms with custom enemies, which were incorrectly not adding to the danger count of the room.
=> RPG: Prevent Tendry snoring in the presence of enemy characters

FrontEndLib/FlashMessageEffect.cpp
Fix flashing text color opacity being unset, causing inconsistent results. What value of opacity it was using was essentially random, whatever value happened to be in that part of memory at that time.
This is the same as #631 but for classic DROD instead of RPG.
I believe this is the cause of https://forum.caravelgames.com/viewtopic.php?TopicID=46235
=> Fix unset flashing text opacity

FrontEndLib/FlashMessageEffect.cpp
Fix flashing text color opacity being unset, causing inconsistent results. What value of opacity it was using was essentially random, whatever value happened to be in that part of memory at that time.
=> RPG: Fix flashing text color opacity being unset

drodrpg/DROD/GameScreen.cpp
RPG doesn't change the music based on the room's danger level, and code to do so had been commented out. However the danger level was still pointlessly recalculated when the music was set.
=> RPG: Remove pointless variable assignment

drodrpg/DROD/EditSelectScreen.cpp
There's an option to display characters as their identity instead of a generic character in the editor. This change also applies this setting to the room preview widget in the main editor screen.
=> RPG: Apply character preview option to main editor screen

drodrpg/DROD/CharacterDialogWidget.cpp
Fix error in the clipboard pasting of the Set Monster Var command that was overwriting parameter w with the stat amount
=> RPG: Fix clipboard paste of set monster var

drodrpg/DRODLib/Combat.cpp
During the auto-stair walk, enemy damage is shown as 0 because the damage calculation gets interrupted by the level exit flag saying combat is halted.
=> Fix incorrect damage preview displayed during level exit

drodrpg/DRODLib/DbRooms.cpp
Prevent an assert failure when a firetrap turns itself off by moving the processing of destroying mist before it processes blowing up bombs and kegs. This caused it to turn into an off firetrap before checking if it was allowed to destroy mist.
=> RPG: Prevent Assert failure when firetrap turns itself off

drodrpg/DRODLib/Monster.cpp
"Attack when adjacent" behaviour cannot attack when movement is blocked, but the same was not also true of "attack when back is turned" behaviour. This copies across the same check to "attack when back is turned".
https://forum.caravelgames.com/viewtopic.php?TopicID=46269
=> RPG: Only allow attacking when back is turned if movement is not blocked

drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/Data/Help/1/keyboard.html
- Adds a pop-out menu for health potions in the editor
- Empty equipment slots aren't described, fixing an issue where they would get a tooltip saying they were metal
- Holding control when right-clicking suppresses the tooltip, only showing highlighting
- "Surprise from behind" is now included in monster descriptions when appropriate
=> RPG: Small UI improvements

drodrpg/DRODLib/Character.cpp
When a character with "Attack in front" attacks, it now checks to see if its base type is an eye, and if so, sends an "Evil eye woke" event. However, if the character doesn't have a `pCustomChar` set, the game crashes.
The logic has been made more robust to prevent this problem.
=> RPG: Fix crash with Attack in front behavior

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/PlayerStats.cpp, drodrpg/DRODLib/PlayerStats.h, drodrpg/DRODLib/TileConstants.h, drodrpg/Data/Help/1/script.html
Ports over the following function primitives that exist in TSS to RPG:
- `_facing` - The orientation that is closest to the given (x,y) vector
- `_rotateDist` - How many rotations are between (o1,o2)
- `_ArrowDir` - Which way is an arrow at (x,y) pointing
- `_RoomTile` - The tile type at (x,y,layer)
- `_MonsterType` - Type of monster at (x,y)
- `_CharacterType` - Type of NPC at (x,y)
=> RPG: Add six additional function primitives

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/EquipmentDescription.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/Monster.h, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
More behaviours that change how stuff interacts with thigns in the room:
- `Cut tarstuff anywhere`, which is effectively the spear behaviour, allowing any tarstuff to be damaged on any tile.
- `Wall and mirror safe` which stops the player from breaking things
- `Heatproof` and `Fireproof` which protect from hot tiles and firetraps respectively
- `Mist protection` which negates mist's DEF nullifying properties
=> RPG: Add more room interaction behaviours

drodrpg/Data/Help/1/script.html
Help files for new behaviours in last commit had some minor copy/paste errors.
=> RPG: Fix minor typos in help for new behaviours

FrontEndLib/TextBox2DWidget.cpp
When editing a scroll in the editor, you get a text box that might eventually scroll down. As soon as you scrolled down any amount so that the first line scrolled off the top, clicking on any line of text always set the cursor to the start of the line.
This was happening because it used a binary search to narrow down on the correct location in the line, but included a check on the y position despite us only changing the x position as part of the binary search. As soon as you scrolled, this y check always passed, meaning the binary search kept going for the maximum length of time, always ending up at the start of the line.
This bug is also present in classic DROD, but only reported for RPG because the scrolls are bigger and so fit more text there.
Thread: …
=> RPG: Fix scrolled text boxes setting cursor by pos incorrectly

drodrpg/DRODLib/Combat.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h
If a piece of equipment is disabled, it's behaviours that affect combat shouldn't apply.
I'm fairly certain this change won't break anything. In addition to require very specific circumstances to manifest, I think most of these behaviours are used in published holds, in part because people are unaware of what they do.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=46292
=> RPG: Fix disabled equipment retaining combat abilities

drodrpg/DROD/DrodScreen.cpp, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/RoomData.h
When pressing F3 or F4 on the primary editor screen to see stats about the level or hold, the equipment slots could appear as the best in-slot for each equipment type. Now they won't.
=> RPG: Don't count slots as the best equipment for stats

drodrpg/Texts/EditScreens.uni
When I added the new swords I forgot to add the entries to EditScreens.uni
=> RPG: Add new sword names to EditScreens.uni

drodrpg/DROD/RoomWidget.cpp
Animations can move a monster's sword out of the room area. It needs to be clipped to prevent a crash.
Forum thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46261
=> RPG: Ensure monster sword is clipped during animations

FrontEndLib/TextBox2DWidget.cpp
#664 broke clicking further to the right of a line of text, setting the cursor at the start of the next line instead of the end of the current one. This fixes that.
Forum thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45919
=> RPG: Fix clicking beyond the end of scrollable text box lines

drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DROD/TileImageCalcs.cpp
Also:
* Rename method params to match var types (also, the inner 'wRow' var was previously shadowing the method parameter of the same name, which makes things harder to maintain and it confused the MSVS debugger when displaying var values).
* Clean up a bad comment. Clarify stair position return vals.
* Remove unnecessary use of magic values to break out of loops.
We could port these changes to 5.x, but I expect they would not be very discernible on the smaller stair tiles.
=> RPG: Smoother lighting effect across the two steps displayed on each stair tile.

drodrpg/DRODLib/Monster.cpp, drodrpg/DRODLib/TileConstants.h
Note this is a change in behaviour from classic DROD where they can't lay eggs on firetraps regardless of state, but here there is a difference in intended function for eggs, being immovable barriers. It seems nice to have a tile queens can lay onto that has a way to clear that one egg without having the required stats.
This does not allow them to lay an egg on an active firetrap, with the same reasoning of them not being able to lay on a hot tile: the queen knows the egg will just immediately take damage.
=> RPG: Allow queen to spawn on closed firetraps

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbRooms.cpp
Fighting mothers bypasses the usual monster defeat code because we often don't want to kill them, however the expansion of post-combat growing elements lived there. This adds those growths to the special case carved out for fighting mothers.
Forum thread: https://forum.caravelgames.com/viewboard.php?BoardID=277
While I was there, found an edge case where clicking on a bomb in the editor could cause a crash if it reaches any tarstuff because there's no CurrentGame instance when simulating a bomb explosion.
=> RPG: Trigger post-combat growths when fighting mothers

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h
Fixing yet another fallout of fixing this rotten bug:
https://forum.caravelgames.com/viewtopic.php?TopicID=40625
When copying a character, were were only updating the logical identity of the character, and not its identity and initial identity, which are used to figure out which default script to run.
I don't like the look of having to triple the arguments into the static method SyncCustomCharacterData but was unsure how else to deal with the fact it's static.
=> RPG: Update identity variable when copying a character

DROD/RoomWidget.cpp, DRODLib/Monster.cpp, DRODLib/Monster.h
Changes to allow invisible inspectable monsters were causing multi-tile monsters to only display on tooltips if the main, non-piece monster was right-clicked. The position check has been updated to also check for pieces.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46306
=> Fix tooltip for multi-tile monsters

DRODLib/DbDemos.cpp
`CDbDemo::GetTimeElapsed` has an assert with a comment that suggests zero-turn demos shouldn't get that far. So return early in that case, since a demo with no turns logically takes zero time.
=> Make CDbDemo::GetTimeElapsed return early for empty demos

drodrpg/DRODLib/CurrentGame.cpp
If a piece of equipment is disabled, it's behaviours shouldn't apply. This fixes all the behaviours not covered by #666.
(A spider test was run on a branch of 1.2.9 to determine how this would effect existing scores.)
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=46292
=> RPG: Fix disabled equipment retaining abilities

drodrpg/DROD/GameScreen.cpp
If you collect a piece of custom equipment, the damage calculation when remotely viewing another room doesn't update until you actually move to another room.
The cause of this is a little trap in how remote room viewing works. The current game is copied, including its monster list, which holds custom equipment characters. However, part of setting up the remote room includes restarting the room, which sets the monster list to be the start of room version, which doesn't match the current game state if custom equipment has been collect after room entry.
To fix, we just need update the room start monster list to be the same as the current list before any restarting, which `CDbSavedGame` helpfully has a function for.
https://forum.caravelgames.com/viewtopic.php?TopicID=45906
=> RPG: Fix bad remote damage calcuation after changing equipment

drodrpg/DRODLib/DbRooms.cpp
When a character has its visibility changed during its lifetime, this was not reflected in room previews as they were checking if the character was invisible before recovering the extra vars for the character.
Forum thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46010
=> RPG: Room previews checking for character visibility too early

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/Monster.cpp, drodrpg/DRODLib/Monster.h, drodrpg/DRODLib/Seep.cpp, drodrpg/DRODLib/Seep.h, drodrpg/Data/Help/1/script.html
Adds the Wall-dwelling behaviour, that makes NPCs die if they aren't on a solid tile, just like seep. To make this work, a few functions have been shuffled around.
As a related change, all monsters with water movement are now labled as "water-dwelling", not just waterskippers.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46193
=> RPG: Add wall-dwelling behavior for NPCs

drodrpg/DROD/RoomWidget.cpp
Characters and rock giants would flicker when cloud shadows were enabled due to their tiles not correctly being marked dirty.
Forum thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45390
=> RPG: Prevent flickering of characters and rock giants with cloud shadows

DRODLib/Character.cpp
Bounds checking isn't being done properly for some script commands, leading to asserts if out-of-bounds areas are provided via _MyScript injection. How this is handled was already handled inconsistently between different commands, so a few different fixes have been done.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=46324
=> Fix bounds checking for some Wait for commands

DROD/EditRoomScreen.cpp, DRODLib/GameConstants.h
The way I classified controls to allow editor and non-editor commands to share key bindings wasn't quite right when it came to commands that interact with chat commands. This is now fixed to allow the optimal chatting experience when playing and editing.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46308
=> Fix command classification breaking chat, demo and help commands

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/DbRooms.cpp
Undo PR #694 and replace with a proper solution. 694 accidentally blew up linking monsters with a NONE identity which had all manner of bad side effects.
This is a another attempt at fixing https://forum.caravelgames.com/viewtopic.php?TopicID=46010
When a character ends their script, there's a brief period of time until you leave the room where the character still exists but the script is done. When you preview another room before leaving the current one, a temporary game is created, but the fact the character's script had ended was not persisted. This caused the room preview to re-process that character's script from the beginning as part of turn 0 processing, which in this case included an Appear command.
=> RPG: Persist when a script has ended

drodrpg/DRODLib/Swordsman.cpp
While fast travel prevents you walking over trapdoors and thin ice, an exception is made for trapdoors for mouse movement pathfinding so you can actually walk on them. This change adds thin ice to that same exception.
=> RPG: Allow mouse movement pathfinding to walk over thin ice

drodrpg/DRODLib/DbRooms.cpp
Certain actions, such as reflecting the room would cause assertions with some new O Layer elements. This is because we had overlooked properly initializing them and updating the values when calling Plot.
=> RPG: Properly initialise and plot new OLayer elements

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CurrentGame.h
Forum thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46392
When room previewing, we need to do a turn 0 process of the scripts in the room, so that e.g. custom monsters will have stats so we can look at them.
Some commands should not work in this case, such as checking if the player is touching an NPC, because they should not be in the room. This PR blocks some important commands form processing in room preview mode. Most importantly are score checkpoints and autosaves. These were submitting (invalid) scores to the spider, and with autosaves you could actually warp to other rooms in the game by loading the newly-created save.
=> RPG: Prevent some script commands processing when room previewing

drodrpg/DRODLib/Monster.cpp
A bit of a weird one.
My local copy of the game would often throw an unhandled exception from the std library when trying to fast travel, but not always. I think I am compiling with a newer version of C++, where the library has some more checks and we were tripping that check.
The pathfinding to find the quickest path to a location implements a custom comparitor. In my version of C++, you must never have a comparitor that, when comparing an item vs itself, result in the comparitor saying it is less than itself, which the one we implemented would do. When it compares the left vs right side, it does a check where it then compares the right vs left and ensures it doesn't get the same result, which it did.
To fix this I've changed A >= B to B < A, which is exactly the same except when A = B. …
=> RPG: Flip pathfinding comparitor

drodrpg/DRODLib/CurrentGame.cpp
When you load a saved game that has no detail rooms on the minimap from the basic map item pickup, we might want to convert some of those to preview rooms if we have since explored it on a different save.
=> RPG: When loading a game, convert mapOnly rooms to preview rooms

drodrpg/DRODLib/Character.cpp
Fix regression caused by #702 .
We had an issue where an ended character script would restart if you scrolled into the room you're currently in in preview mode. To fix this, I persisted the bScriptDone flag and made scripts not process if this was true. But I overlooked that End on Room Exit also sets this flag.
Now we only stop processing the script if this flag is set if we're in room preview mode, which was the specific use case we were originally trying to avoid..
=> RPG: Fix regression that stopped End on Room Exit working correctly

drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/CurrentGame.cpp
If a player previews a room containing mist at the coordinate the player is standing, it would affect all of the damage calculations. This stops mist impacting player stats when the player is not in that room.
A bug is also fixed where the player was not considered outside that room when you previewed a room by clicking on the minimap, only when scrolling into the room via room preview mode.
=> RPG: Prevent mist affecting player during room preview

drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbBase.h
For active development, it's useful to have a way to update existing database views without having to create new `dat` files. metakit allows that to be done with `c4_Storage::GetAs`, which changes the view it gets. A new function has been added to `DbBase` which does this for all views for a `dat` file.
For safety, the redefinition call is gated behind `#ifdef`, and can be enabled by defining `REDEFINE_DATABASE`.
=> RPG: Add function that can update views to current definitions

DROD/SettingsScreen.cpp, DROD/SettingsScreen.h, DRODLib/DbBase.cpp, Texts/MIDs.h, Texts/SettingsScreen.uni
The people want to disable cloud sync sometimes. This adds a button to do that, and makes it so that you can reactivate the sync afterwards without having to delete your data.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=42719
=> Add ability to toggle cloud sync activation

drodrpg/DROD/CharacterDialogWidget.cpp
=> RPG: Ensure InitialIdentity is correct when changing character type in editor

drodrpg/DRODLib/DbRooms.cpp
#719 missed out the export and import bits for overhead images. So they're in this PR.
=> RPG: Add ExportXML and SetProperty cases for overhead images

drodrpg/DRODLib/DbSavedGames.cpp
Lighting information for explored rooms was being written out after the tag was closed. This results in malformed xml that wouldn't be parseable.
=> RPG: Fix xml export of lighting from explored rooms

drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RestoreScreen.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DRODLib.2019.vcxproj, drodrpg/DRODLib/DRODLib.2019.vcxproj.filters, drodrpg/DRODLib/Db.cpp, drodrpg/DRODLib/Db.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/DbHolds.cpp, drodrpg/DRODLib/DbLocalHighScores.cpp, drodrpg/DRODLib/DbLocalHighScores.h, drodrpg/DRODLib/DbPlayers.cpp, drodrpg/DRODLib/DbProps.h, drodrpg/DRODLib/DbRefs.cpp, drodrpg/DRODLib/DbRefs.h, drodrpg/DRODLib/DbXML.cpp, drodrpg/DRODLib/ImportInfo.h, drodrpg/Texts/GameScreen.uni, drodrpg/Texts/MIDs.h
Adds support for storing a user's best score for a score point locally. These records are stored in new database view, with new management objects `CDbLocalHighScore` and `CDbLocalHighScores`. Each record corresponds to a specific player's score for a specific scorepoint in a specific hold. Along with the raw score value, the player's stats are also recorded (but the stats are currently not used for anything). This view is stored as part of the saved games data file.
When a scorepoint command is executed, the game will now create a new high score record if none exists, or update the existing one if the player's score is greater than the current recorded score. If online score submission is disabled, a message will also be shown.
The scorepoints dialog now uses high score records to …
=> RPG: Add local score storage

DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/CurrentGame.cpp
At some point I changed how character's default behaviors (and movement types) were set so that they would be set on non-zero turns, to fix a problem with generated characters. This broke game snapshots in a subtle way.
The fix to the fix is to make the defaulting turn zero only, and to manually call those functions on generated characters.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46201
=> Fix how default behaviors are set for characters

DROD/GameScreen.cpp
After a restart, the rewind limit turn is set to the current turn number. However, the check for the rewind limit uses the player turn number, meaning the amount of undos is reduced if "turnless" actions have been performed. The limit should always be set using the player turn.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46519
=> Fix inconsistency with rewind limit logic

DROD/CharacterDialogWidget.cpp, DRODLib/Character.cpp, DRODLib/Character.h, DRODLib/CharacterCommand.cpp, DRODLib/CharacterCommand.h, DRODLib/DbBase.cpp, DRODLib/DbHolds.cpp, Data/Help/1/scriptarray.html, Texts/MIDs.h, Texts/Speech.uni
Due to how arrays work, it is difficult to search them. Two new commands `Wait for array entry` and `Count array entries` allow all values that have been set in an array to be checked against a condition.
`DoesArrayVarSatisfy` and `CountArrayVarEntries` have been implemented using lambdas and `std::function`. It's possible to do this without them, but it's look messier and is harder to read. (I did restrain myself slightly and didn't start using `auto` whenever a variable declaration started getting too long for my liking)
=> Add commands to query entire array variables

DROD/CharacterDialogWidget.cpp
I accidentally broke default script editing in #726, making it so the fix script edited would always be shown. This PR fixes the fix.
=> Fix initial populating of default scripts

DRODLib/BuildUtil.cpp
#737 for master branch, to allow the possibility of a 5.1 MacOS build with this fix.
=> Fix out of bounds error in BuildUtil::BuildTilesAt

DROD/CharacterDialogWidget.cpp, DROD/CharacterDialogWidget.h, DROD/EditRoomScreen.cpp, DROD/EditRoomWidget.h, DROD/GameScreen.cpp, DROD/MapWidget.h, DRODLib/Character.cpp, DRODLib/CharacterCommand.h, DRODLib/CueEvents.h, DRODLib/DbBase.cpp, Data/Help/1/script.html, Texts/EditScreens.uni, Texts/MIDs.h, Texts/Speech.uni
Allows rooms to be explored without sending the player to them. This action isn't reversed by undoing a move or restarting a room, because the infrastructure to support undoing adding explored rooms is definitely not worth the effort.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=41625
=> Add "Add room to map" command

drodrpg/DRODLib/CurrentGame.cpp
If an already explored room was passed to `CCurrentGame::AddRoomToMap`, it would get reset due to a minor oversight. Now there is a check for the passed room being unexplored that needs to be met for the original room to be loaded.
=> RPG: Fix explored rooms getting overwritten in CCurrentGame::AddRoomToMap

DROD/CharacterDialogWidget.cpp, DRODLib/BuildUtil.cpp, DRODLib/DbRooms.cpp, DRODLib/DbRooms.h, DRODLib/Platform.cpp, DRODLib/Platform.h
New platforms of both types can now be constructed in rooms, either directly with the Build command, or via build markers. Constructed platforms will merge with existing platform, and this can allow multiple platforms to merge into a single platform.
A minor technical note is that merging platforms can leave behind empty platforms. This isn't entire ideal, but the same thing can happen when building over platforms, so it doesn't appear to have any detrimental effects.
=> Add support for building platforms via scripting

DROD/DROD.2019.vcxproj, DROD/DROD.2019.vcxproj.filters, DROD/DrodEffect.h, DROD/DrodFontManager.cpp, DROD/DrodFontManager.h, DROD/GameScreen.cpp, DROD/MovementOrderHintEffect.cpp, DROD/MovementOrderHintEffect.h, DROD/RoomWidget.cpp, DROD/RoomWidget.h, DROD/SettingsScreen.cpp, DRODLib/Character.cpp, DRODLib/DbBase.cpp, DRODLib/GameConstants.cpp, DRODLib/GameConstants.h, DRODLib/SettingsKeys.cpp, DRODLib/SettingsKeys.h, Data/Help/1/keyboard.html, Texts/MIDs.h, Texts/SettingsScreen.uni
Based on the damage and item preview effects for RPG, movement order can now be displayed directly on monsters. It's a key-togglable effect, since it's not information that's always relevant.
Monster remains don't show order, but do get counted (which is needed to match with the order shown when right-clicking). Maybe order should be shown for construct remains, since that can matter. Fegundo ashes do get the effect, since they're counted as alive.
The performance gets a little bad once the monster counter gets high enough, probably due to how many surfaces are getting created. Not sure if that can be streamlined.
=> Add togglable movement order hint effects

DROD/DemoScreen.cpp, DROD/EditRoomScreen.cpp, DROD/GameScreen.cpp, DROD/RoomWidget.cpp, DROD/RoomWidget.h, DROD/SettingsScreen.cpp, DRODLib/DbBase.cpp, DRODLib/SettingsKeys.cpp, DRODLib/SettingsKeys.h, Texts/MIDs.h, Texts/SettingsScreen.uni
It's been remarked that way citizens are described in the tile tooltip can be confusing, since the group number looks like a movement order number. Since we now have color strings, we can reuse them for the purpose of describing citizens and relay stations.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46525
=> Add option to describe citizen groups with colors

DRODLib/MonsterType.h
An interaction some people find weird. I'm not sure how strongly intentioned it is, although puff-safety is something that has to be specifically given to a monster type.
It might not affect published rooms to change this.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45458
=> Make Seep killable by Puffs

DRODLib/Slayer.cpp
A weird oversight: If a slayer wants to open an a door, finds a path to an orb, then fails to find a path to a plate, it gets stuck. This is because if it fails to find a path to a plate, `pathToDest` will have a size of zero, which is always less than any valid orb path.
A small change is needed to actually verify that a path a plate was found, and if not, the orb path should be used if it exists.
=> Fix slayer incorrectly discarding path to orb

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/DROD.2019.vcxproj, drodrpg/DROD/EffectChangeHistory.h, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/GameScreen.h, drodrpg/DROD/RoomWidget.h, drodrpg/DROD/drod.2019.vcxproj.filters, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CueEvents.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/Texts/MIDs.h
A few tweaks and fixes to improve map icons:
1. "White key" is now named "Skeleton key" on the interface. This leaves a spare string rattling around. For the moment I've shuffled some message ids around, and I have a thing in the pipeline that happens to need a single string, so I'll fully replace it at that point.
2. Adding icons to the map now has its own cue event instead of using the map room reveal event.
3. Icons are now tracked so that they can be properly updated during room resets.
4. Some tracking has been added to `CGameScreen` to make sure the map widget redraws correctly when undoing or restarting. `EffectChangeHistory` is no longer just for lighting. (It also now lives in its own file.)
=> RPG: Fix issues with map icons

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
The much desired command to hurt things. It can even be configured to consider or ignore the target's defense value. Percentage damage isn't directly supported, but should be easily achieved with _MyScript overrides. Part of the reason this command is helpful is because #717 means that using `Set monster var` now has side-effects when used on serpents.
(There are also a few things missed from the map icon work in here)
=> RPG: Add Attack tile command

drodrpg/DROD/EquipmentDescription.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbBase.cpp, drodrpg/Texts/Speech.uni
Requested change, along with a rename. It makes sense, as applying it to other equipment can lead to strange situations when equipment is disabled.
=> RPG: Make Removes Sword behaviour only apply on weapons

drodrpg/DRODLib/CurrentGame.cpp
Specifically, don't update monster state for what's being displayed in the room being exited; only update it in the copy being saved to the explored room state.
=> RPG: Fix character state being reset during level exit animation.

drodrpg/DROD/EditRoomScreen.cpp, drodrpg/Texts/SettingsScreen.uni
I zapped the safety case for saving a room in the editor when using ALT-F4 becasue I didn't understand what I was looking at. Also, I gave one the messages the wrong id in `SettingsScreen.uni`. Fixing them up here.
=> RPG: Fix up keybinding work mistakes

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CharacterCommand.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/TileConstants.h, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
While keys are technically one item, from a user-facing perspective having them as an item group is nicer.
=> RPG: Add item groups for keys and collectables

DRODLib/Character.cpp, DRODLib/Clone.cpp, DRODLib/Clone.h, DRODLib/Construct.cpp, DRODLib/DbRooms.cpp, DRODLib/Mimic.cpp, DRODLib/Monster.cpp, DRODLib/Monster.h, DRODLib/PlayerDouble.h, DRODLib/Swordsman.cpp, DRODLib/Swordsman.h, DRODLib/TemporalClone.cpp, DRODLib/TemporalClone.h
The implementation of this behavior turned out to be pretty naive. Mainly because the three things it effects (swordsman, clones, timeclones) are all slightly inconsistent in what can step on them. This should hopefully iron things out so that they can be mangled by the correct things when the behavior override isn't active.
=> Fix issues with body attack immune player behavior

drodrpg/DRODLib/CurrentGame.cpp
Due to C++ being how it is, the wrong version of `DbPackedVars::GetVar` ends up being used. This causes an assert because the int version of the function doesn't like how the var has the size of a int64.
=> RPG: Fix wrong overload in CCurrentGame::getTextForInputCommandKey

FrontEndLib/Sound.cpp, FrontEndLib/Sound.h, drodrpg/DROD/EditRoomScreen.cpp, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/GameScreen.h, drodrpg/DROD/RoomScreen.cpp, drodrpg/DROD/RoomScreen.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbRooms.cpp
- Also migrating 5.x engine sfx volume reduction when playing multiple instances of a sound.
- Change editor placement sound for keys and equipment.
- Allow room editor overwrite of ATK/DEF gem types.
=> Sfx pitch adjustments for similar items.

DRODLib/DbRooms.cpp
Accidentally introduced a new bug in #805. This unbreaks it, preventing the player from stepping on clones or projections if they don't have a body attack.
=> Fix regression allowing player to non-lethally step on clones

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h
In short, ground movement type would never get saved due to being value zero, and monsters with non-ground movement would save it from the editor, causing weirdness if you changed their type. A new flag should fix this issue.
=> RPG: Fix serialization of changed character movement

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/CharacterOptionsWidget.cpp, drodrpg/DROD/CharacterOptionsWidget.h, drodrpg/DROD/EditRoomWidget.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DROD/RoomWidget.h, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/DbBase.cpp, drodrpg/DRODLib/Monster.cpp, drodrpg/DRODLib/Monster.h, drodrpg/DRODLib/PlayerStats.cpp, drodrpg/DRODLib/PlayerStats.h, drodrpg/Data/Help/1/script.html, drodrpg/Texts/MIDs.h, drodrpg/Texts/Stats.uni
A much-desired feature to alter character colours. `_MyHue` sets the hue, and `_MySaturation` sets the saturation. It's quite obvious. They both have value ranges which were picked somewhat arbitarily, and can be changed anytime before release.
It might be nicer to have true hue-shifting, but I ran into some issues with that. For now, setting the hue works, even it sometimes blasts away some details.
=> RPG: Add color-changing predefined vars

drodrpg/DRODLib/Db.cpp, drodrpg/DRODLib/Db.h, drodrpg/DRODLib/DbHolds.cpp, drodrpg/DRODLib/DbXML.cpp, drodrpg/DRODLib/ImportInfo.h
Local high scores are exported as part of players, not saved games or demos. This means that they get destroyed when updating a hold. This is bad.
I've now added the mechanisms required to export and import high score data during a hold update.
=> RPG: Preserve local high scores through hold update

drodrpg/DROD/CharacterDialogWidget.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/Ant.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CueEvents.h, drodrpg/DRODLib/Goblin.cpp, drodrpg/DRODLib/Seep.cpp, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
Fixes missing sfx and not catching this event in scripts.
=> RPG: Add cue event on scripted character back strike.

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbSavedGames.cpp, drodrpg/DRODLib/DbSavedGames.h
The core change is to keep track of mapState for RemoveMappedRoomsNotIn().
=> RPG: Fix rooms with icons revealed by a map element not resetting on room restart.

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DbSavedGames.cpp
ExploredRooms objects should be scanned after checking the current room. Otherwise, the current room may not appear as explored (e.g., when a map icon is defined for the current room, then picking up a map, then restarting the room).
=> RPG: Fix bad logic in IsRoomExplored.

DROD/ImageOverlayEffect.cpp
If a `CImageOverlayEffect` is created with no commands, it will cause a crash when it tries to update. Easily fixed with a sanity check in `CImageOverlayEffect::Update`
=> Fix crash with zero command image overlay

BackEndLib/Wchar.cpp, BackEndLib/Wchar.h, drodrpg/DROD/EquipmentDescription.cpp, drodrpg/DROD/RoomWidget.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/Data/Help/1/script.html
Allows `_MyWeakness` values to be split up using semi-colons, to have multiple weakness categories on the same custom monster or equipment.
=> RPG: Support multiple custom weaknesses

drodrpg/DROD/EquipmentDescription.cpp, drodrpg/DROD/EquipmentDescription.h, drodrpg/DROD/RoomWidget.cpp, drodrpg/DRODLib/DbBase.cpp, drodrpg/Texts/GameScreen.uni, drodrpg/Texts/MIDs.h, drodrpg/Texts/Speech.uni
It's nice if ability descriptions aren't so long they take up more than one line on the combat preview dialog. Some suggestions have been made for how they can be more concise.
This PR also makes it so that Goblin and Wyrm weaknesses use the same verbiage as custom weaknesses, for flawless consistency.
=> RPG: Make some ability descriptions shorter

drodrpg/DROD/GameScreen.cpp
This assert fires when speech can't be reattached to a character. This can happen when a speaking character is killed, and then the player undoes some later moves. Nothing bad happens in this case, and the TSS version of the function doesn't have the assert, so it can probably be removed.
=> RPG: Remove bad assert in CGameScreen::ClearSpeech

drodrpg/DROD/EditRoomScreen.cpp
RPG has both live and dead briar placeable in the editor, but briar's state is entirely dependent upon its connection to a root in RPG, and immediately changes to the correct state on placement. So being able to place both is pointless. Also made it play the briar break sound when placing it.
=> RPG: Remove pointless briar distinction in editor and change SFX

drodrpg/DROD/RoomScreen.cpp
The level multiplier was overlapping with the shovel count when both shovels and the multiplier were large. It turns out the size of the shovel label was also needlessly large.
The new positioning doesn't overlap even with the widest displayed multiplier (x-99999) and widest displayed shovels (999).
=> RPG: Change position of level multiplier

drodrpg/DROD/Main.cpp
Reverts #638 as we've gone back to the original door image.
=> RPG: Revert to old splash screen door positioning

drodrpg/DRODLib/Character.cpp
Expanding #819 to include the other two types of attacking an adjacent player.
=> RPG: Add SFX when custom chararcter strikes adjacent square

drodrpg/DRODLib/DbBase.cpp, drodrpg/Texts/MIDs.h
`MID_MusicElizabeth` and `MID_RemoveTransparentLayer` had the same value, which is bad. Also, there wasn't a entry for `MID_MusicElizabeth` in `DbBase`.
=> RPG: Fix duplicated message id

drodrpg/DRODLib/DbSavedGameMoves.cpp
I missed a use of `CDbXML::z_uncompress`. Fortunately, `CStretchyBuffer::Uncompress` does the same thing, and can be used in place of the removed function.
=> RPG: Remove remaining call to z_uncompress

DROD/DemoScreen.cpp, DROD/GameScreen.cpp, DROD/GameScreen.h, DROD/SettingsScreen.cpp, DRODLib/CueEvents.h, DRODLib/CurrentGame.cpp, DRODLib/DbBase.cpp, DRODLib/SettingsKeys.cpp, DRODLib/SettingsKeys.h, Texts/MIDs.h, Texts/SettingsScreen.uni
Adds a setting that makes a swirl appear when placing a double. The new "Halph effects" are now also configurable, for people who might find them bothersome.
https://forum.caravelgames.com/viewtopic.php?TopicID=46552
=> Add optional swirl effect when placing doubles

DROD/WorldMapWidget.cpp
Using custom characters as world map icons doesn't work correctly. This has two causes:
1. When getting the tile image, the value for the south orientation is passed to `g_pTheBM->GetCustomTileNo` for the x-index. However, the index for a south-facing tile isn't the same as the orientation value. This means the character isn't facing the correct direction. To fix, the correct index should be used.
2. If the custom character doesn't have at least two rows of tiles, the default tile for it's base type is used for its animation frame. This leads to the icon "blinking" between the custom tile and base tile. To fix, we should try to use the default tile row before falling back to the base type's tiles.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46693
=> Fix world map tile images when using non-animated custom character

drodrpg/DROD/WorldMapWidget.cpp
#854 for RPG implementation of world maps
=> RPG: Fix world map tile images when using non-animated custom character

drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/Combat.cpp, drodrpg/DRODLib/Combat.h, drodrpg/DRODLib/CueEvents.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbBase.cpp, drodrpg/Texts/GameScreen.uni, drodrpg/Texts/MIDs.h
There are two problems with changing HP values during combat:
1. Changing enemy HP during combat doesn't work correctly when combat is quick. This is because the code that sets the HP value used by the combat is outside of the main combat loop. This means changing the combat rate setting can affect the outcome of combats, which is bad. Fixed by updating the HP value on each loop iteration when doing quick non-simulated combat.
2. Increasing HP during combat can lead to an endless combat. At the highest combat rate, this can lead to the game freezing up. To fix this, I've introduced "stall tracking". A stall is counted whenever a combatant's HP increases during a round, or they fail to reduce their opponents HP. If *both* combatants have more stalls that a certain threshold (currently at …
=> RPG: Fix problems with changing HP during combat

drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Monster.cpp, drodrpg/Data/Help/1/script.html
Have negative values for ATK and DEF already works in combat calculations. Since there are some fringe uses for them, I've made it work correctly in other places.
=> RPG: Support monsters with negative ATK and DEF

drodrpg/DRODLib/Character.cpp
The commands to wait for player to turn clockwise and counterclockwise stopped working after a refactor to check the player's own variables instead of the copy the character was tracking.
=> RPG: Revert how scripts check player orientation

DRODLib/Slayer.cpp, DRODLib/Slayer.h
Slayers opening doors do some dubious things. While some of these behaviours have been around since 2.0, they're weird and unintuitive enough that they should be changed.
1. A Slayer in the door opening state will ignore a target that is caught by or steps on its wisp. It makes much more sense for Slayers to abandon opening a door in favour of chasing a wisped target. (related thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46689)
2. Slayers in the door opening state will stab explosives. Mowing down guards and other Slayers is slightly weird, but it doesn't harm the Slayer doing it. Stabbing explosives is much less expected. Slayers should avoid stabbing explosives in all cases. This is so obscure and unexpected that the only demo this change breaks is an untended solution …
=> Fix issues with Slayer door-opening state

drodrpg/DROD/TitleScreen.cpp, drodrpg/Data/Help/1/commands.html
Removes the tutorial as an option. Also updates the help files to remove mention of it.
=> RPG: Remove tutorial from main menu options

drodrpg/DRODLib/CurrentGame.cpp
#714 fixed entities being able to push a pushable object with their body and weapon in the same turn. However, this also made it so that objects could only be pushed once each turn, which is a regression.
This is fixed by clearing the pushed object information before processing each monster.
=> RPG: Fix regression with object pushes

drodrpg/DRODLib/Character.cpp
Fixes a regression where monsters with custom identities were not correctly setting their default movement type.
=> RPG: Fix setting default movement type for custom identites

drodrpg/DRODLib/CurrentGame.cpp
Set the value as part of CCurrentGame::RetrieveExploredRoomData to avoid ordering issues with explored rooms being marked as fully explored
=> RPG: Rework how CCurrentGame sets bIsNewRoom

drodrpg/DROD/DrodScreen.cpp, drodrpg/DROD/HoldSelectScreen.cpp, drodrpg/DROD/LevelStartScreen.cpp, drodrpg/DROD/WinStartScreen.cpp, drodrpg/DRODLib/DbHolds.cpp, drodrpg/DRODLib/DbHolds.h, drodrpg/DRODLib/DbLevels.cpp, drodrpg/DRODLib/ImportInfo.h
Replaces the `Main` status with `Tendry`, and adds a new `ACR` status. Additionally, where required, checks for the `Main` status have been replaced with `CDbHold::IsOfficialHold`.
=> RPG: Update hold status for new official hold

drodrpg/DROD/GameScreen.cpp
For the benefit of non-standard key bindings for e.g. the combat preview dialog, so the preview isn't immediately ended when holding don the modifier key.
=> RPG: Allow modifier keys to be used on room previews

drodrpg/DRODLib/DbLocalHighScores.cpp
Having a local high score that can't be matched to hold record in a player file that's being imported is not expected, but it shouldn't cause the import to be cancelled.
=> RPG: Don't block player import due to holdless high score

DRODLib/CurrentGame.cpp
If you start recording a temporal split on the same turn a cutscene starts, `CCurrentGame::cutSceneStartTurn` will get set to the original turn number when you rewind back, rather than the current turn number. This means that if you undo the rewind, the game reverts all the way back to the start of recording. This can be fixed by updating the tracking after a rewind.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46771
=> Fix problem with rewinding temporal split into cutscene start

drodrpg/DRODLib/BuildUtil.cpp
I believe this is the cause of Mac crashing when building virtual tiles, which have a negative tile number
=> RPG: Bounds check before accessing TILE_LAYER array index

drodrpg/DROD/MapWidget.cpp
Right-clicking the minimap for hidden rooms caused the floor colour to be different than for other rooms. Now it's consistent.
=> RPG: Make map marker colours for secret rooms consistent

drodrpg/DROD/DrodScreen.cpp, drodrpg/DRODLib/DbPlayers.cpp
When a player is loaded, we run through their key settings and convert them from the old style to the new 5.2 style which allows modifier keys. This change also makes it save down a default setting if the key setting does not exist.
This can happen when a new player is created and hasn't yet opened the settings screen, or the profile is an old one that didn't have all the expanded keybinds that weren't previously configurable.
Due to various refactors to support these new style keybinds, trying to convert these into text for e.g. displaying on scrolls would not work if the key wasn't saved down into the player's settings blob. This change ensures they are always present.
=> RPG: When loading new style keybinds, save a default if none present

drodrpg/DROD/RoomWidget.cpp
If you have a cutscene playing with a player role of None, and the room is dark enough to have a player light, then right-clicking during the cutscene would cause the cursor light source to not clear each time you clicked or moved the mouse. This is because the code to maintain the active light source and tiles affected by it was wrapped inside a block to get the current light holder, and it wasn't considered to have one because of player role None.
=> RPG: Fix cursor light during cutscene with none player role

drodrpg/DROD/Main.cpp
When a style is not present, the game defaults to the default style, and uses its default music. When a style is present but its graphics are missing, it uses the deep spaces graphics, but when the music file is missing, the music simply fails to switch to the default and keeps playing what is current.
This makes the demo seem bugged, as e.g. the game continues to play the title music when playing a hold architected in another room style.
By completely removing the other styles from the demo, the fallbacks work correctly.
=> RPG: Remove styles from demo ini to ensure music fallback works

drodrpg/DROD/DrodSound.cpp
Update the default volume slider to values that I think work better, especially to make the speech more legible.
=> RPG: Update default volume sliders to values that I prefer

drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/DbRooms.cpp, drodrpg/DRODLib/DbRooms.h
Since the front end code uses `CDbRoom::pushed_objects` to decide how to animate pushed objects, clearing it mid-turn breaks the animations. So I've split out the tracking to prevent multi-pushes into a new member, `CdbRoom::moved_objects` which only needs to care about positions.
=> RPG: Separate pushed object tracking for logic and drawing

drodrpg/Data/Help/1/extendedtoc.html
#908 fixed a bad tag in the extended help file doc then broke it in two other places, doh! Now it's fixed for real.
=> RPG: Fix entended TOC help doc, again

drodrpg/DROD/RestoreScreen.cpp
Two changes to make it easier to check for and discuss missing scorepoints:
1. Scorepoint names are not obscured for holds you can edit
2. Rather than all scorepoints being obscured as "???", alphanumeric characters in the scorepoint name are instead replaced with question marks.
3. 
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=41708
=> RPG: Tweak display of unearned scorepoints on scorepoint dialog

drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/RoomWidget.h
Reported as a bug, although it looks like RPG just didn't support this
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46824
=> RPG: Make move counter persist between sessions

drodrpg/DROD/EditSelectScreen.cpp
Porting over a fix from classic DROD that stops the editor crashing when you try to rearrange the level list, a regression introduced by the world map feature.
=> RPG: Port over fix for level rearranging

drodrpg/DROD/GameScreen.cpp, drodrpg/DROD/MapWidget.cpp, drodrpg/DROD/MapWidget.h, drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/DRODLib/DRODLib.2019.vcxproj, drodrpg/DRODLib/DRODLib.2019.vcxproj.filters, drodrpg/DRODLib/DbSavedGames.h, drodrpg/DRODLib/TotalMapStates.cpp, drodrpg/DRODLib/TotalMapStates.h
Part 1 of trying to fix the endless plague of bug reports at map states not persisting correctly across play sessions. I'm splitting this into 2 PRs to get some earlier feedback about the current state of things, and as a backup because I've been working on it for a while. This PR implements everything except saving and loading the saved game.
As outlined at https://forum.caravelgames.com/viewtopic.php?TopicID=46823&page=0#454693 my plan to fix this endless stream of bugs is to create a new saved game whose purpose is to keep track of the best room state a player has seen a room in. This saved game will be saved every time it is updated, so that persistence is guaranteed.
Room map states are updated in 3 occasions:
1) We enter a room not in preview mode (set to Explored)
2) We pick up a …
=> RPG: Part 1 of alternative way of tracking map states

drodrpg/DRODLib/DbPackedVars.cpp
When importing an old player profile we need to replace old key bindings with new ones in the new extended format. To do this we find a var, then unset and set a new value it. Unfortunately, unsetting it caused lastQueryIter to point at an invalid location.
=> RPG: Reset LastQueryIter when unsetting packed var

DROD/Main.cpp
A couple of changes to exceptions in `Main.cpp`:
1. Made it so we're catching `std::exception` rather than `CException`. This allows exceptions that don't inherit from `CException` to be caught and processed (which should be all of them).
2. If we do catch an exception not derived from `std::exception`, log that an unknown exception was encountered.
=> Tweak main-level exception handling

drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/DbHolds.cpp
The hold status enum had been previously refactored to change the value Main to two other values, Tendry and ACR. Two instances of Main still existed inside some code that wasn't built or analysed due to be wrapped inside a STEAMBUILD ifdef, which will have caused an issue when trying to produce a Steam build.
=> RPG: Fix Steam uses of CDbHold::Main

drodrpg/Texts/Buttons.uni, drodrpg/Texts/DemosMessages.uni, drodrpg/Texts/DemosScreen.uni, drodrpg/Texts/EditScreens.uni, drodrpg/Texts/Export.uni, drodrpg/Texts/FileAccess.uni, drodrpg/Texts/GameScreen.uni, drodrpg/Texts/Import.uni, drodrpg/Texts/KeyDescriptions.uni, drodrpg/Texts/RestoreScreen.uni, drodrpg/Texts/SelectScreens.uni, drodrpg/Texts/SettingsScreen.uni
Like #845 but for RPG. Things were even worse in some places - the `!!translate` tag was the entire entry for some strings. Usefully, all the strings with these tags in the RPG `.uni` files had translations available in the TSS files, so I could reuse the translations as needed.
The one difference I noticed was that the French translations for TSS and RPG translate 'hold' differently. TSS uses 'antre', while RPG used 'oubliette'. To make things easier I've made RPG consistent with TSS.
=> RPG: Clean up strings containing !!translate

DRODLib/DbXML.cpp
Deleting the temp files as part of `CDbXML::CleanUp()` means they can get deleted between importing demos and importing saves. Which is bad because it means saves won't get preserved. Moved the call to fix this.
=> Fix timing with clearing of import temporary files

BackEndLib/InputKey.h
For whatever reason, trying to compile a Steam build doesn't work because of the `#include <BackEndLib/Types.h>` line in `InputKey.h`. Every other include of `Types.h` uses quote includes so I've changed the problem line to match.
=> Change include type in InputKey.h

DRODLib/CurrentGame.cpp
There is an oversight in `CCurrentGame::SetTurn` that can cause the room lock state to be changed. When a game snapshot is used, the lock state is recorded in a temporary variable, and then set back. However, #195 made a change so that by the time this happens, `CCurrentGame::bRoomExitLocked` has already been set to false, and it's value recorded in a different variable. If a snapshot is used, the function returns before the lock state is set back.
To fix this, we should reset the lock state using the `bOldIsRoomLocked` value once the game state has been updated from a snapshot.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46295
=> Fix room lock being unset when updating game from snapshot

drodrpg/DRODLib/Combat.cpp, drodrpg/DRODLib/Combat.h
The no enemy defense behaviour was missed during the refactor of making checks for weapon behaviours properly account for being disabled and being on a small weapon.
https://forum.caravelgames.com/viewtopic.php?TopicID=46925
=> RPG: Fix No Enemy Defense behaviour on small weapons

DROD/CharacterDialogWidget.cpp, DROD/CharacterOptionsWidget.cpp, DROD/DemoScreen.cpp, DRODLib/Character.cpp, DRODLib/CurrentGame.cpp, DRODLib/GameConstants.h
There are several places in the code where `min` and `max` take arguments that aren't the same type. These don't work if they're defined as `std::min` and `std::max`. This is generally happening when one of the values is a constant.
I've gone through and fixed up all the ones that aren't using the same type, generally by adding the special indicators that mark a constant as not being an `int`.
(In theory we might be able to remove the weird hack in `Ports.h` by now but I haven't done that for the sake of avoiding more problems later.)
=> Fix uses of min/max to work with standard functions

drodrpg/DROD/GameScreen.cpp, drodrpg/DRODLib/CurrentGame.cpp
Fixes two bugs:
1) Introduced a regression that stopped you from pathfinding to a preview room, (this was caused by an accidental flipping of the logic):
https://forum.caravelgames.com/viewtopic.php?TopicID=46935
2) When loading or starting a new game, the preview room states were only loaded from the default player id, as it happens before the members are set on the current game object:
https://forum.caravelgames.com/viewtopic.php?TopicID=46943
=> RPG: Fix two issues with room preview states

DROD/DemoScreen.cpp
A couple more uses of `INT`, which is a Windows-only type, managed to sneak into the code. Based on context, they should be `UINT` instead.
=> Remove use of Windows-only INT type

BackEndLib/Assert.h, DROD/DROD.2019.vcxproj, DROD/DrodScreen.cpp, DROD/DrodScreen.h, DRODLib/Character.cpp, DRODLib/DRODLib.2019.vcxproj
The MSVC compiler lets you get away with certain things that other compilers don't. The `/permissive-` compiler flag makes things stricter, which has revealed some problems to fix:
- The ternary expression we use for asserts has two different return types, which is bad. Fixable by replacing the 0 with a `void()`
- `DrodScreen::InitKeysymToCommandMap`'s argument is a non-const ref. This causes issues in certain cases. Since it doesn't need to be non-const I've made it const
- Setting a string to be equal to a char array via `=` operator is apparently bad. Fixed the one place doing this by using the constructor.
- Some weird template error I don't understand on line 3203 of `Character.cpp`. Fixed by adding a `const`.
I've gone ahead and added the `/permissive-` flag to the DROD and DRODLib …
=> Allow compilation with /permissive- flag

drodrpg/DROD/CharacterDialogWidget.cpp
The command is still using an older way to get the level entrance ID, which doesn't work. Updated it to use the current way.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46980
=> RPG: Fix UI for Go to level entrance command

drodrpg/DROD/GameScreen.cpp
It was possible to skip the dying state being deactivated by undoing during the death sequence.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46981
=> RPG: Fix face widget getting stuck in dying state

drodrpg/DROD/DrodScreen.cpp
Port across a fix from classic drod for a crash related to the bomb explosion visual cue.
https://forum.caravelgames.com/viewtopic.php?TopicID=46986
=> RPG: Port over fix for bomb explosion visual cue crash

drodrpg/DROD/RoomWidget.cpp
Adds the base ATK and DEF of an in-room equipment to it's tooltip description, with the change it has to the overal stats in parentheses.
=> RPG: Add more information to in-room equipment tooltip

drodrpg/DRODLib/Character.cpp, drodrpg/DRODLib/Character.h, drodrpg/DRODLib/CurrentGame.cpp, drodrpg/DRODLib/CurrentGame.h, drodrpg/Data/Help/1/script.html
Makes the three logical wait commands able to perform the delaed event check if they fail while containing one or more `Wait for event` commands. The help for `Wait for event` has also been made more detailed.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=47038
=> RPG: Improve logical wait interaction with Wait for event 

drodrpg/DRODLib/BuildUtil.cpp
It shouldn't be possible to build mist on walls, closed doors, dirt blocks or hot tiles, since it can't be placed on those kinds of tiles or expand onto them during gameplay.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=47057
=> RPG: Add build restrictions for mist

drodrpg/DROD/GameScreen.cpp
Serpents use their own types of cue event when defeated in combat, so the flag to redraw previews isn't set after fighting one. The flag should also be set if either `CID_SnakeDiedFromTruncation` or `CID_MonsterPieceStabbed` have occured.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=47060
=> RPG: Correctly update damage previews after serpent fight

drodrpg/DROD/GameScreen.cpp
Effects that start on turn zero currently animate even when level entrance text is displayed. This is prevented in TSS by freezing effects in `CGameScreen::SetForActivate`. This PR ports that fix to RPG.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46998
=> RPG: Freeze room widget effects in CGameScreen::SetForActivate
