CaravelGames/drod

DRODLib/Ghost.cpp
DRODLib/Slayer.cpp
DRODLib/Waterskipper.cpp
DRODLibTests/DRODLibTest.2013.vcxproj
DRODLibTests/src/tests/Monsters/Seep/SeepAttackWeaponBlock.cpp
DRODLibTests/src/tests/Monsters/Slayer/SlayerBodyKillBlocked.cpp
DRODLibTests/src/tests/Monsters/Waterskipper/SkipperAttackWeaponBlock.cpp

Fix for: http://forum.caravelgames.com/viewtopic.php?TopicID=43242

Block Seep/Waterskipper/Slayer bodykills with blocking weapons.

---

DRODLib/CurrentGame.cpp

Fix for http://forum.caravelgames.com/viewtopic.php?TopicID=41406
This is probably the best way to deal with this issue while prevent evil architects from doing horrible things.

Cancel temporal recording if the player's role changes.

---

DROD/EditRoomScreen.cpp
FrontEndLib/ObjectMenuWidget.cpp
FrontEndLib/ObjectMenuWidget.h
FrontEndLib/Widget.cpp
drodrpg/DROD/EditRoomScreen.cpp
drodrpg/DROD/Main.cpp

Fix inexplicable room editor menu crash in CEditRoomScreen::SetSelectedObject.

---

drodrpg/DROD/CharacterDialogWidget.cpp

Forum topic: http://forum.caravelgames.com/viewtopic.php?TopicID=40970

Expose scripting option to build and wait for hard wall item.

---

DRODLib/BuildUtil.cpp
DRODLib/BuildUtil.h
DRODLib/Character.cpp
DRODLib/TileConstants.h

Remove superfluous logic check.

Build tiles minor code cleanup.

---

drodrpg/DRODLib/Character.cpp
drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/CurrentGame.h
drodrpg/DRODLib/DbRooms.cpp
drodrpg/DRODLib/DbRooms.h
drodrpg/DRODLib/Swordsman.cpp
drodrpg/DRODLib/Swordsman.h

(Migrated TeleportPlayer and related code from DROD 5.x, including refactoring code into ProcessPlayerMoveInteraction.)

RPG Fix: script var changes to player position weren't working.

---

DRODLib/Bridge.cpp
DRODLib/DbRooms.cpp
DRODLibTests/DRODLibTest.2019.vcxproj
DRODLibTests/DRODLibTest.2019.vcxproj.filters
DRODLibTests/src/CAssert.cpp
DRODLibTests/src/CAssert.h
DRODLibTests/src/Runner.cpp
DRODLibTests/src/Runner.h
DRODLibTests/src/tests/Elements/Bridges.cpp
DRODLibTests/src/tests/Monsters/Aumtlich/GenericAumtlich.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44763&page=0#435516)

Turn zero processing bugs

---

DRODLib/Character.cpp
DRODLib/CurrentGame.cpp
DRODLibTests/DRODLibTest.2019.vcxproj
DRODLibTests/DRODLibTest.2019.vcxproj.filters
DRODLibTests/src/tests/Player/TurnZero/StairsOnTurnZero.cpp
DRODLibTests/src/tests/Scripting/GoToLevelEntrance.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44764)

Walking down stairs will no longer happen on turn 0

---

DRODLib/Briar.cpp
DRODLib/DbRooms.cpp
DRODLibTests/src/CAssert.cpp
DRODLibTests/src/CAssert.h
DRODLibTests/src/tests/Elements/Briars.cpp

[Relevant thread.](http://forum.caravelgames.com/viewtopic.php?TopicID=38484&page=0#435580)

Briar magical connections

---

DRODLib/Briar.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=39320)

Briars consuming light posts will now remove their light from the room

---

DRODLib/Station.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=40956)

Citizens will no longer move across gentryi chains diagonally

---

DRODUtil/Util3_0.cpp
Scripts/DRODUTIL_rebuild_dat.bat
drodrpg/DRODUtil/Util3_0.cpp

(We now have version control to tell us this.)
Add script to rebuild mids.h and barebones .dat file.

Remove adding "New" message when rebuilding MIDs file.

---

DROD/GameScreen.cpp
drodrpg/DROD/GameScreen.cpp

Also micro refactor to original PR.

Copy PR #141 to RPG.

---

DRODLib/CurrentGame.cpp
DRODLibTests/DRODLibTest.2019.vcxproj
DRODLibTests/DRODLibTest.2019.vcxproj.filters
DRODLibTests/src/tests/Elements/GreenGate.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44794&page=0#435939)

Fixed a bug I introduced that caused green gate to auto open on turn 1

---

BackEndLib/BackEndLib.2019.vcxproj
CaravelNet/CaravelNet.2019.vcxproj
DROD/DROD.2019.vcxproj
DROD/GameScreen.cpp
DRODLib/DRODLib.2019.vcxproj
DRODLibTests/DRODLibTest.2019.vcxproj
DRODUtil/DRODUtil.2019.vcxproj
FrontEndLib/FrontEndLib.2019.vcxproj
drodrpg/CaravelNet/CaravelNet.2019.vcxproj
drodrpg/DROD/drod.2019.vcxproj
drodrpg/DRODLib/DRODLib.2019.vcxproj
drodrpg/DRODUtil/DRODUtil.2019.vcxproj

VS2019: Multi-processor compilation and incremental compilation for all build configurations.

---

DROD/CharacterDialogWidget.cpp
FrontEndLib/ListBoxWidget.cpp
FrontEndLib/ListBoxWidget.h

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=39931)

Deleting many commands will be now much faster

---

DRODLib/Character.cpp
DRODLib/Character.h
DRODLib/CurrentGame.cpp
DRODLib/CurrentGame.h
DRODLib/DbRooms.cpp
DRODLib/MonsterType.h

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44441)

Wait for Entity and Generate Entity will now work with Evil Eye (Active)

---

DRODLib/Character.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=41135)

Pushable-by-body NPCs no longer gain hot tile resistance

---

DRODLib/BuildUtil.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44809)

It is now possible to build walls under gentryii chains

---

DROD/EditRoomScreen.cpp
DROD/EditRoomWidget.cpp
DRODLib/TileConstants.h

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=42160)

Editor placements

---

DROD/TemporalMoveEffect.cpp
DROD/VerminEffect.cpp
DROD/VerminEffect.h
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/VerminEffect.cpp
drodrpg/DROD/VerminEffect.h

Fix compiler warnings.
Vermin micro optimizations.

Copy PRs 182 and 183 to RPG.

---

DRODLib/DbRooms.cpp

[Relevant post](https://forum.caravelgames.com/viewtopic.php?TopicID=39404&page=0#436472)

Falling gentryii do not produce random swords anymore

---

DRODLib/PlayerStats.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=40998)

Fixed variable reference generation

---

DROD/FaceWidget.cpp
DROD/FaceWidget.h
DROD/GameScreen.cpp
DROD/RoomWidget.cpp

[Relevant post](https://forum.caravelgames.com/viewtopic.php?TopicID=38410&page=0#436572)

Fixed Beethro never waking up

---

DRODLib/Character.cpp
DRODLib/Swordsman.h
DRODLibTests/DRODLibTest.2019.vcxproj
DRODLibTests/DRODLibTest.2019.vcxproj.filters
DRODLibTests/src/tests/Monsters/ArmedMonsters/DisarmedArmedMonsters.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=41053)

It is now possible to Turn Into Monster disabled armed monsters

---

DROD/GameScreen.cpp

[Related thread](http://forum.caravelgames.com/viewtopic.php?TopicID=40817)

No victory sound is shout is played when player role is none now

---

drodrpg/DRODLib/CurrentGame.cpp

[Relevant thread](https://forum.caravelgames.com/viewtopic.php?TopicID=44819)

RPG: Fix var multiplication rounding errors.

---

DROD/DrodScreen.cpp
DRODLib/DbXML.cpp
DRODLib/DbXML.h

This PR implements incremental uncompression of the compressed XML buffer during parsing to keep memory footprint low.
I really like how it turned out.

XML import memory optimization

---

DROD/FaceWidget.cpp
DROD/GameScreen.cpp
FrontEndLib/BitmapManager.cpp
FrontEndLib/BitmapManager.h
FrontEndLib/EventHandlerWidget.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44824)
Posting as draft since it depends on changes from #228. Will update once it's merged.

Effect pausing

---

drodrpg/DRODLib/CurrentGame.cpp

[Relevant topic](https://forum.caravelgames.com/viewtopic.php?TopicID=44917)

RPG fix: Teleport accessories not interacting with room at destination tile.

---

DROD/GameScreen.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=40821)

Play video woes

---

BackEndLib/BackEndLib.2019.vcxproj.filters
DROD/DROD.2019.vcxproj.filters
DRODLib/DRODLib.2019.vcxproj.filters
DRODUtil/DRODUtil.2019.vcxproj.filters
FrontEndLib/FrontEndLib.2019.vcxproj.filters
drodrpg/DROD/drod.2019.vcxproj.filters
drodrpg/DRODLib/DRODLib.2019.vcxproj.filters
drodrpg/DRODUtil/DRODUtil.2019.vcxproj.filters

Feel free to update these filters if something's not right.

VS 2019: Add project filters (file folder hierarchy).

---

drodrpg/DRODLib/Character.cpp
drodrpg/DRODLib/Character.h
drodrpg/DRODLib/DbRooms.cpp
drodrpg/DRODLib/DbSavedGames.cpp
drodrpg/DRODLib/Monster.cpp
drodrpg/DRODLib/Monster.h

[Relevant topic](http://forum.caravelgames.com/viewtopic.php?TopicID=44922)

RPG: Fix regression in PR 37: Character settings and scripts don't get exported

---

DRODLib/DbRooms.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44790)

Daggers no longer prevent tar babies to spawn from unstable tar

---

BackEndLib/CoordSet.h
DROD/GameScreen.cpp
DROD/GameScreen.h
DROD/RoomWidget.cpp
DRODLib/GameConstants.cpp
FrontEndLib/Sound.cpp
FrontEndLib/Sound.h
drodrpg/DROD/RoomWidget.cpp
drodrpg/DRODLib/GameConstants.cpp

[Relevant topic](http://forum.caravelgames.com/viewtopic.php?TopicID=44747)
Most notably, make multiple instances of the same SEID quieter when playing simultaneously.
Smooth fading out of orb activation flash.
Also, a missed UnicodeToUTF8 change.

Sfx refinements.  Misc others.

---

drodrpg/DROD/DrodSound.cpp
drodrpg/DROD/DrodSound.h
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/Main.cpp

Also remove some obsolete commented out code.

RPG: Add sfx for ATK/DEF/HP pickups.

---

DROD/CharacterDialogWidget.cpp
DROD/RoomWidget.cpp
DROD/RoomWidget.h
DRODLib/Character.cpp
DRODLib/Character.h
DRODLib/DbBase.cpp
DRODLib/PlayerStats.cpp
DRODLib/PlayerStats.h
DRODUtil/Util3_0.cpp
Data/Help/1/script.html
Texts/MIDs.h

Depends on PR #303, will undraft once it's merged.
[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=42750)

Added _MyColor variable, identical to what is already in RPG

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DROD/DrodScreen.h
drodrpg/DROD/EditRoomScreen.cpp
drodrpg/DROD/EditRoomWidget.cpp
drodrpg/DROD/EditSelectScreen.cpp
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/GameScreen.h
drodrpg/DROD/RoomEffectList.cpp
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/RoomWidget.h
drodrpg/DROD/SettingsScreen.cpp
drodrpg/DROD/ZombieGazeEffect.cpp
drodrpg/DRODLib/BuildUtil.cpp
drodrpg/DRODLib/DRODLib.2019.vcxproj
drodrpg/DRODLib/DRODLib.2019.vcxproj.filters
drodrpg/DRODLib/OrbUtil.cpp
drodrpg/DRODLib/OrbUtil.h

Migrated:
- Room rendering improvements.
- Door building orb association fixes.
- Multi-command deletion optimization.
- Editor serpent placement bug fix.
- Settings screen audio fixes.
Changed settings screen death sound.

RPG: Migrate fixes from 5.1.1 PRs.

---

drodrpg/DRODLib/Swordsman.cpp

BTW, copied this code from 5.1.1.

RPG: Fixed tweening on room restart when player role is None.

---

drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/CurrentGame.h

[Relevant bug post](https://forum.caravelgames.com/viewtopic.php?TopicID=44943&page=0#437514)

RPG: Fix NPC defeated on tarstuff doesn't process "Wait for defeat" commands.

---

drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/MapWidget.cpp
drodrpg/DROD/MapWidget.h
drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/CurrentGame.h
drodrpg/DRODLib/DbSavedGames.cpp
drodrpg/DRODLib/DbSavedGames.h

[Relevant forum post](https://forum.caravelgames.com/viewtopic.php?TopicID=42615&page=0#437540)

RPG: Fix issues with room preview list and display.

---

drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/DbSavedGames.cpp
drodrpg/DRODLib/DbSavedGames.h

[Relevant issue post](https://forum.caravelgames.com/viewtopic.php?TopicID=42615&page=0#437540)

RPG: Fix game ExploredRooms state not synchronized on game save/load.

---

DRODLib/CurrentGame.cpp
DRODLib/CurrentGame.h
DRODLib/Stalwart.cpp

[Relevant thread](http://forum.caravelgames.com/viewtopic.php?TopicID=44955&page=0)

Demo checking bugs

---

DROD/RoomWidget.cpp

[url=http://forum.caravelgames.com/viewtopic.php?TopicID=44956]Relevant thread[/url]

Fixed turn counter not appearing (or rather immediately disappearing)

---

DROD/EditRoomWidget.cpp
DROD/RoomWidget.cpp
DROD/RoomWidget.h
DRODLib/DbRooms.cpp
DRODLib/DbRooms.h
drodrpg/DROD/RoomWidget.cpp

Plus LowPassLightFilter fix. [Topic](https://forum.caravelgames.com/viewtopic.php?TopicID=44962)

Migrate light rendering fixes from RPG.

---

DROD/RoomWidget.cpp
drodrpg/DROD/RoomWidget.cpp

RPG: Remove superfluous lighting pass on water tiles.

---

DROD/Main.cpp
DRODLib/SettingsKeys.cpp
DRODLib/SettingsKeys.h
Data/Help/1/customizing.html
FrontEndLib/EventHandlerWidget.cpp
FrontEndLib/Screen.cpp
FrontEndLib/Screen.h

- Full Screen mode
- Allowing resizing of the game window
- Automatically minimizing the game when alt tabbing on full-screen
[Relevant thread](https://forum.caravelgames.com/viewtopic.php?TopicID=44965)

Added three new INI options:

---

drodrpg/DROD/Main.cpp
drodrpg/DRODLib/SettingsKeys.cpp
drodrpg/DRODLib/SettingsKeys.h

RPG: Migrate PR #344.

---

drodrpg/DRODLib/Character.cpp
drodrpg/DRODLib/Character.h
drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/CurrentGame.h
drodrpg/DRODLib/PlayerStats.cpp
drodrpg/DRODLib/PlayerStats.h
drodrpg/Data/Help/1/refindex.html
drodrpg/Data/Help/1/script.html

Implement _EnemyStat(x,y,stat) primitive for use in script expressions.
Super easy to add new primitives going forward  See [here](https://github.com/CaravelGames/drod/pull/354/files#diff-7236b719adebbea66df2152d26dee8766a53c30ae1d75c7f657041cf0f047f30R140).
Edit: more primitives added

RPG: Add script expression parsing support for primitive functions with parameter lists.

---

DROD/RestoreScreen.cpp

Small quality of life feature to allow the author of a hold to always see which rooms challenges are located in.

Hold author always sees challenge locations

---

DROD/EditRoomWidget.cpp

Mostly allowing more placements, but some restrictions were added. See the commits for details. Also fixes an issue with placing Gentryii under swords.
Related thread 1: http://forum.caravelgames.com/viewtopic.php?TopicID=45435
Related thread 2: http://forum.caravelgames.com/viewtopic.php?TopicID=45438

Tweak a bunch of editor placement restrictions

---

DROD/CharacterDialogWidget.cpp
DROD/GameScreen.cpp
DRODLib/Character.cpp
DRODLib/CueEvents.h
DRODLib/CurrentGame.cpp
DRODLib/DbBase.cpp
DRODLib/GameConstants.cpp
DRODLib/GameConstants.h
DRODLib/Mimic.cpp
Data/Help/1/keyboard.html
Data/Help/1/script.html
Texts/MIDs.h
Texts/SettingsScreen.uni

It's two more special commands. Along with a few changes to manage there now being more than one.
Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45873

Add two more special commands

---

drodrpg/DRODLib/Swordsman.cpp

Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=45907

RPG: Allow player sword on crate during quick travel

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DROD/CharacterDialogWidget.h
drodrpg/DROD/DROD.2019.vcxproj
drodrpg/DROD/DrodDialogs.cpp
drodrpg/DROD/DrodDialogs.h
drodrpg/DROD/DrodScreen.h
drodrpg/DROD/EditRoomScreen.cpp
drodrpg/DROD/EditRoomScreen.h
drodrpg/DROD/Main.cpp
drodrpg/DROD/SelectMediaDialogWidget.cpp
drodrpg/DROD/SelectMediaDialogWidget.h
drodrpg/DROD/drod.2019.vcxproj.filters
drodrpg/DRODLib/DbBase.cpp
drodrpg/DRODLib/DbHolds.cpp
drodrpg/DRODLib/DbHolds.h
drodrpg/DRODLib/SettingsKeys.cpp
drodrpg/DRODLib/SettingsKeys.h
drodrpg/Texts/EditScreens.uni
drodrpg/Texts/MIDs.h

Improves the management of custom media files:
- Files can be replaced with a file of the same type, maintaining references
- Adding sound to speech connects to media manager
- Sounds and speech are correctly removed when changing a command's type

RPG: Port improved media management options from TSS 5.2

---

DROD/RoomWidget.cpp
drodrpg/DROD/RoomWidget.cpp

g++ 12 creates a compile error on narrowing the int.

Fix cast int->unsigned int

---

drodrpg/DROD/CharacterDialogWidget.cpp

The RPG version of #491. The dialog is enlarged, the listboxes are larger, and the variable UI has been rearranged to increase the amount of space in the value box.

RPG: Enlarge Add Command dialog

---

FrontEndLib/ListBoxWidget.cpp
FrontEndLib/ListBoxWidget.h
drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DROD/CharacterDialogWidget.h
drodrpg/DROD/CommandListBoxWidget.cpp
drodrpg/DROD/CommandListBoxWidget.h
drodrpg/DROD/DROD.2019.vcxproj
drodrpg/DROD/drod.2019.vcxproj.filters

This is the RPG version of #357. The script editor is now better:
- Line numbers are displayed
- There are "if lines" when the code is indented in If blocks and complex conditionals.

RPG: Improve command listbox

---

.gitignore
CompilingDrod_Win.md
DROD/GameScreen.cpp
DROD/ImageOverlayEffect.cpp
DROD/RoomWidget.cpp
DRODLib/Briar.cpp
DRODLib/Briar.h
DRODLib/BuildUtil.cpp
DRODLib/Character.cpp
DRODLib/CharacterCommand.cpp
DRODLib/CharacterCommand.h
DRODLib/Clone.cpp
DRODLib/DbRooms.cpp
DRODLib/DbXML.cpp
DRODLib/DbXML.h
DRODLib/GameConstants.cpp
Data/Help/1/character.html
FrontEndLib/Effect.h
FrontEndLib/EventHandlerWidget.cpp
FrontEndLib/PNGHandler.cpp
FrontEndLib/TextEffect.cpp
FrontEndLib/TextEffect.h
Scripts/InstallDependencies.win32.vs2013.py
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/RoomWidget.cpp
readme.md

Some merge conflicts had to be ironed out, which all related to input related changes:
- The numpad issues are solved by skell's upgraded control mappings, which means the alternative key lookup is not needed.
- The issue with long waits remain. Due to git being git, some work was needed to move the location of the fix.
The build number has also been updated for convience.

Update tss-5.2-dev with latest 5.1.1 changes

---

drodrpg/DROD/DrodBitmapManager.cpp
drodrpg/DROD/EditRoomScreen.cpp
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/GameScreen.h
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/RoomWidget.h
drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/CurrentGame.h

In anticipation of a possible 1.2.9 release, this moves some fixes and code-only UI improvements into the main branch.

Backport RPG bugfixes from 1.3 branch

---

drodrpg/DROD/Main.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45388

RPG: Allow high DPI on SDL window

---

drodrpg/DRODLib/Swordsman.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=26959

RPG: Account for Removes Sword behavior in quick travel

---

DRODLib/Clone.cpp
DRODLib/PlayerDouble.cpp
DRODLib/TemporalClone.cpp
drodrpg/DROD/DrodBitmapManager.cpp
drodrpg/DROD/EditRoomScreen.cpp
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/GameScreen.h
drodrpg/DROD/Main.cpp
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/RoomWidget.h
drodrpg/DROD/SettingsScreen.cpp
drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/CurrentGame.h
drodrpg/DRODLib/GameConstants.cpp
drodrpg/DRODLib/GameConstants.h
drodrpg/DRODLib/Swordsman.cpp
drodrpg/Data/Help/1/script.html

Merging up with the master branch. Only a few TSS commits but keeping up is important.

Update TSS 5.2 branch

---

.gitmodules
DRODLib/Character.cpp
DRODLib/DbXML.cpp
DRODLib/Monster.cpp
Scripts/InstallDependencies.win32.vs2013.py
drodrpg/DROD/GameScreen.cpp

Gets the new build-related changes for Linux + metakit, along with the fix to the `Move To` crash.

Update 5.2 dev branch to latest master

---

drodrpg/DROD/GameScreen.cpp

Repeated entries on the battle preview dialog are avoided by keeping a record of the monster types already shown, along with the full stats of any scripted monsters. With additional monster customisation present in 1.3, this can now lead to some monsters being ignored.
To fix this, all monsters now have their full stats recorded, and scripted characters also have their name recorded. This covers the situation where the stats of a predefined monster are altered, and when monsters have the same stats but different names.
Related thread: http://forum.caravelgames.com/viewtopic.php?TopicID=27954

RPG: Rework battle preview dialog uniqueness checks

---

DROD/DemoScreen.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46088

Fix demo playback ending a turn early

---

DROD/RoomWidget.cpp

Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=46149

Add highlighting for invisible temporal projections

---

DRODLib/Character.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46148

Allow wall movement characters to be pushed through solid tiles

---

Scripts/InstallDependencies.win32.vs2013.py

Fix some minor errors encountered when running the script

Minor fixes to dependency script

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DROD/DROD.2019.vcxproj
drodrpg/DROD/DrodEffect.h
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/PuffExplosionEffect.cpp
drodrpg/DROD/PuffExplosionEffect.h
drodrpg/DROD/drod.2019.vcxproj.filters
drodrpg/DRODLib/DbBase.cpp
drodrpg/Texts/MIDs.h
drodrpg/Texts/Speech.uni

Ports across the puff explosion effect from classic DROD

RPG: Add Puff Explosion Effect

---

drodrpg/DROD/ParticleExplosionEffect.cpp

Fix for recently-added floor tile layer stuff blocking blood splatter particle effects.

RPG: Fix new floor tiles from blocking blood splatters

---

drodrpg/DROD/Main.cpp
drodrpg/DRODLib/GameConstants.cpp

Update RPG version to "2.0.0.#-dev"

Update Door splash image positioning.

---

FrontEndLib/Screen.cpp
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/GameScreen.h

Fix tooltip flicker on fast room travel. 

---

FrontEndLib/FontManager.cpp
FrontEndLib/FontManager.h
drodrpg/DROD/DrodFontManager.cpp
drodrpg/DROD/TitleScreen.cpp
drodrpg/DROD/TitleScreen.h
drodrpg/DRODLib/DbBase.cpp
drodrpg/Texts/TitleScreen.uni

Updated menu color to LightCyan.
Refactor DROD RPG 1 title screen rendering into new method.
Simplify "Back" menu text.

RPG: Add new title screen image.

---

drodrpg/DROD/DrodFontManager.cpp
drodrpg/DROD/TitleScreen.cpp

Requires updated BG image version to work correctly.

RPG: Update title menu color to Gold. Increase lantern light intensity.

---

drodrpg/DROD/TitleScreen.cpp
drodrpg/DROD/TitleScreen.h

RPG: Add Caravel logo animation.

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DROD/EditRoomScreen.cpp
drodrpg/DROD/EquipmentDescription.cpp
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/TileImageCalcs.cpp
drodrpg/DROD/TileImageConstants.h
drodrpg/DRODLib/BuildUtil.cpp
drodrpg/DRODLib/Character.cpp
drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/DbBase.cpp
drodrpg/DRODLib/RoomData.h
drodrpg/DRODLib/TileConstants.h
drodrpg/Data/Help/1/equipment.html
drodrpg/Texts/MIDs.h

Add 3 new weapons: Dagger, Staff and Spear. There will be an accompanying PR in the data repo.

RPG: Add 3 new weapons: Dagger, Staff and Spear

---

FrontEndLib/TextBox2DWidget.cpp

Port over scrolled text box fix to classic drod

---

drodrpg/DROD/RoomWidget.cpp

Classic DROD: Clip monster swords during animations

---

FrontEndLib/TextBox2DWidget.cpp

#678 for classic DROD
Forum thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45919

Classic DROD: Fix clicking beyond the end of scrollable text box lines

---

DRODLib/DbRooms.cpp

Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=46318

Add missing break in CDbRoom::RemoveMonsterDuringPlayWithoutEffect

---

drodrpg/DRODLib/Character.cpp

Similar to #698, but for RPG commands.

RPG: Fix bounds checking for some Wait for commands

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DROD/EditRoomScreen.cpp
drodrpg/DROD/EquipmentDescription.cpp
drodrpg/DROD/EquipmentDescription.h
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/TileImageCalcs.cpp
drodrpg/DROD/TileImageConstants.h
drodrpg/DRODLib/BuildUtil.cpp
drodrpg/DRODLib/Character.cpp
drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/DbBase.cpp
drodrpg/DRODLib/RoomData.h
drodrpg/DRODLib/TileConstants.h
drodrpg/Data/Help/1/equipment.html
drodrpg/Texts/EditScreens.uni
drodrpg/Texts/MIDs.h

Adds 3 new stock shields.
Also reorganizes the swords in the editor to be in power order.
There will be an accompanying PR in the data repo.

RPG: Add 3 new stock shields

---

drodrpg/DRODLib/Character.cpp
drodrpg/DRODLib/DbRooms.cpp
drodrpg/DRODLib/Monster.h
drodrpg/DRODLib/Serpent.cpp
drodrpg/DRODLib/Serpent.h

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46003

RPG: Fix how serpent HP resets after Set monster var is used

---

DROD/CharacterDialogWidget.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46463

Fix position resetting when editing default script

---

DROD/DemoScreen.cpp

Thread: http://forum.caravelgames.com/viewtopic.php?TopicID=46478

Fix demo playback advancing by two moves with CMD_DEMO_NEXT

---

drodrpg/DRODLib/DbLocalHighScores.cpp
drodrpg/DRODLib/DbLocalHighScores.h
drodrpg/DRODLib/DbXML.cpp

A couple of things that slipped through the net plus a mistake that needs fixing.

RPG: Fix some problems with importing local high scores

---

drodrpg/DRODLib/CurrentGame.cpp
drodrpg/DRODLib/CurrentGame.h

For master branch to allow a 1.2 version to be released with this fix.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46292

RPG: Fix disabled equipment behaviours still applying

---

drodrpg/DROD/RoomWidget.cpp

RPG: Ensure monster sword is clipped during animations

---

DROD/HoldSelectScreen.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46118

More immediate presentation of Steam DLC import notice

---

DRODLib/Character.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=44745

Fix wall light making Activate Item At non-blocking for orb/plate

---

DROD/GameScreen.cpp
DROD/RoomWidget.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46102

Make clones in remotely viewed rooms match player role

---

DROD/RoomWidget.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45736

Show move preview for frozen temporal projections

---

DROD/DemoScreen.cpp
DROD/GameScreen.h

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46225

Follow "Show Subtitles when Voices Play" setting in demo replay

---

DRODLib/Gentryii.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=45400

Fix bad interaction between stationary gentryii and arrow

---

drodrpg/DROD/DrodBitmapManager.cpp
drodrpg/DROD/DrodBitmapManager.h
drodrpg/DROD/DrodScreen.cpp
drodrpg/DROD/Main.cpp
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/SettingsScreen.cpp
drodrpg/DRODLib/DbBase.cpp
drodrpg/Texts/MIDs.h
drodrpg/Texts/SettingsScreen.uni
drodrpg/Texts/Speech.uni

(And also add a few missed lines for map icon transparency)

RPG: Add configurable tarstuff transparency

---

BackEndLib/Wchar.cpp
BackEndLib/Wchar.h
FrontEndLib/FontManager.cpp
FrontEndLib/FontManager.h
FrontEndLib/LabelWidget.cpp
FrontEndLib/LabelWidget.h
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/RoomWidget.cpp
drodrpg/DROD/RoomWidget.h
drodrpg/DROD/TileImageConstants.h

Requires new tiles from drodrpgData repo.

RPG: Revise combat and scorepoint dialogs to display stat icons.

---

DROD/CharacterDialogWidget.cpp
DRODLib/Character.cpp
DRODLib/CharacterCommand.h
DRODLib/DbBase.cpp
Data/Help/1/script.html
Texts/MIDs.h
Texts/Speech.uni

Sometimes, you want a character to appear on a tile with a weapon. This allows that to happen.
Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=43320

Add "Can Appear On Weapons" behavior

---

drodrpg/DROD/DrodFontManager.cpp
drodrpg/DROD/DrodFontManager.h
drodrpg/DROD/GameScreen.cpp
drodrpg/DROD/RoomScreen.cpp
drodrpg/Texts/EditScreens.uni
drodrpg/Texts/GameScreen.uni
drodrpg/Texts/SettingsScreen.uni

Sidebar text display improvements

---

DRODLib/DbRooms.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46655

Fix tokens losing type when covered by built item

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DRODLib/Character.cpp
drodrpg/DRODLib/Character.h
drodrpg/DRODLib/CharacterCommand.cpp
drodrpg/DRODLib/CharacterCommand.h
drodrpg/DRODLib/DbBase.cpp
drodrpg/DRODLib/PlayerStats.cpp
drodrpg/DRODLib/PlayerStats.h
drodrpg/Data/Help/1/scriptarray.html
drodrpg/Texts/MIDs.h
drodrpg/Texts/Speech.uni
drodrpg/Texts/Stats.uni

#735 for DROD RPG. Also adds the `_ReturnX` predefined var, which previously wasn't required by any commands.

RPG: Add commands to query entire array variables

---

drodrpg/DROD/ImageOverlayEffect.cpp

RPG: Fix crash with zero command image overlay

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DRODLib/BuildUtil.cpp
drodrpg/DRODLib/BuildUtil.h
drodrpg/DRODLib/DbBase.cpp
drodrpg/DRODLib/DbRooms.cpp
drodrpg/DRODLib/TileConstants.h
drodrpg/Texts/MIDs.h
drodrpg/Texts/Speech.uni

RPG: Support removal of transparent layer objects with build commands

---

drodrpg/DROD/EditRoomScreen.cpp

Also add highlighting of staircases with the "return to prior location" destination

RPG: Fix crash with staircase highlighting in editor

---

DROD/EditRoomScreen.cpp
DROD/EntranceSelectDialogWidget.h

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46712

Allow stair destination selection to be cancelled

---

FrontEndLib/DialogWidget.cpp
FrontEndLib/TextBox2DWidget.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46717

Support using Ctrl-Enter to okay text editing dialog

---

FrontEndLib/DialogWidget.cpp
FrontEndLib/TextBox2DWidget.cpp

Picking #857 over to RPG development branch.

RPG: Support using Ctrl-Enter to okay text editing dialog

---

DROD/CharacterDialogWidget.cpp
DROD/RoomWidget.cpp
DROD/RoomWidget.h
DRODLib/Character.cpp
DRODLib/Character.h
DRODLib/DbBase.cpp
DRODLib/PlayerStats.cpp
DRODLib/PlayerStats.h
Data/Help/1/script.html
FrontEndLib/BitmapManager.cpp
FrontEndLib/BitmapManager.h
Texts/MIDs.h
Texts/Stats.uni

The new colour-shifting features from RPG, now for TSS.
A line up of technicolour goblins using `_MyHue`:

And hue and saturation predefined vars

---

drodrpg/DRODLib/DbRooms.cpp
drodrpg/DRODLib/TileConstants.h

Fix issue where grappling hook jumps considered some collectables on the target square to be blocking.

RPG: Fix grappling onto pickup items

---

drodrpg/DRODLib/DbHolds.cpp
drodrpg/DRODLib/DbLevels.cpp
drodrpg/DRODLib/DbLocalHighScores.cpp
drodrpg/DRODLib/DbPlayers.cpp
drodrpg/DRODLib/DbPlayers.h
drodrpg/DRODLib/DbSavedGames.cpp
drodrpg/DRODLib/ImportInfo.h

- All the required wiring for multi-ID player matching
- Fix some wrong maps and id use in `CDbLocalHighScore::SetProperty`

RPG: Fix more issues with importing player files

---

DRODLib/DbPackedVars.cpp

Reset LastQueryIter when unsetting packed var

---

drodrpg/DROD/GameScreen.cpp

See https://forum.caravelgames.com/viewtopic.php?TopicID=46926

RPG: Prevent oscillation after grappling with mouse movement

---

drodrpg/DROD/CharacterDialogWidget.cpp
drodrpg/DROD/CharacterOptionsWidget.cpp
drodrpg/DRODLib/Character.cpp

RPG: Fix uses of min/max to work with standard functions

---

drodrpg/DRODLib/DbRooms.cpp

https://forum.caravelgames.com/viewtopic.php?TopicID=46942

RPG: Prevent mist blocking movement accessories

---

FrontEndLib/MenuWidget.cpp
FrontEndLib/MenuWidget.h

https://forum.caravelgames.com/viewtopic.php?TopicID=46927

RPG: Prevent mouse movement being interpreted as intent to click option

---

drodrpg/DRODLib/BuildUtil.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46971

RPG: Fix built explosion not detonating powder keg

---

drodrpg/DRODLib/CurrentGame.cpp

Thread: https://forum.caravelgames.com/viewtopic.php?TopicID=46967

RPG: Include effect of invisibility and speed potion during room previews
